// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package adminmodel

import (
	"kratos-admin/pkg/toolbox/datax"
)

const TableNameAdminGroup = "admin_group"

// AdminGroup 管理员团队
type AdminGroup struct {
	datax.BaseEntity
	Name           string `gorm:"column:name;type:varchar(32);not null;comment:团队名称" json:"name"`                                          // 团队名称
	Status         int32  `gorm:"column:status;type:tinyint(4);not null;default:2;comment:状态: 1 下线, 2 在线" json:"status"`                   // 状态: 1 下线, 2 在线
	DataIsolation  int32  `gorm:"column:data_isolation;type:tinyint(4);not null;default:1;comment:数据隔离: 1 不隔离, 2 隔离" json:"dataIsolation"` // 数据隔离: 1 不隔离, 2 隔离
	UserPrivileges string `gorm:"column:user_privileges;type:json;not null;comment:用户数据权限" json:"userPrivileges"`                          // 用户数据权限
	OperatorId     int64  `gorm:"column:operator_id;type:bigint(20);not null;comment:操作人id" json:"operatorId"`                             // 操作人id
	Deleted        bool   `gorm:"column:deleted;type:tinyint(1);not null;comment:是否删除" json:"deleted"`                                     // 是否删除
	DramaIsolation int32  `gorm:"column:drama_isolation;type:tinyint(4);not null;default:1;comment:短剧隔离 1:不隔离 2:隔离" json:"dramaIsolation"` // 短剧隔离 1:不隔离 2:隔离
}

// TableName AdminGroup's table name
func (AdminGroup) TableName() string {
	return TableNameAdminGroup
}
