// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package adminmodel

import (
	"kratos-admin/pkg/toolbox/datax"
)

const TableNameAdminUser = "admin_user"

// AdminUser 管理员用户
type AdminUser struct {
	datax.BaseEntity
	Username    string `gorm:"column:username;type:varchar(32);not null;uniqueIndex:uk_username,priority:1;comment:用户名" json:"username"` // 用户名
	Nickname    string `gorm:"column:nickname;type:varchar(32);not null;index:idx_nickname,priority:1;comment:昵称" json:"nickname"`       // 昵称
	Phone       string `gorm:"column:phone;type:varchar(32);not null;uniqueIndex:uk_phone,priority:1;comment:手机号" json:"phone"`          // 手机号
	Email       string `gorm:"column:email;type:varchar(32);not null;comment:邮箱" json:"email"`                                           // 邮箱
	Avatar      string `gorm:"column:avatar;type:varchar(1024);not null;comment:头像" json:"avatar"`                                       // 头像
	Status      int32  `gorm:"column:status;type:tinyint(4);not null;comment:状态 1:正常 2:注销" json:"status"`                                // 状态 1:正常 2:注销
	Password    string `gorm:"column:password;type:json;comment:用户密码" json:"password"`                                                   // 用户密码
	Extra       string `gorm:"column:extra;type:json;comment:用户拓展信息" json:"extra"`                                                       // 用户拓展信息
	IsOptimizer int32  `gorm:"column:is_optimizer;type:tinyint(4);not null;comment:优化师标识，0 非优化师，1 优化师" json:"isOptimizer"`               // 优化师标识，0 非优化师，1 优化师
	OperatorId  int64  `gorm:"column:operator_id;type:bigint(20);not null;comment:操作人id" json:"operatorId"`                              // 操作人id
}

// TableName AdminUser's table name
func (AdminUser) TableName() string {
	return TableNameAdminUser
}
