// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package adminmodel

import (
	"kratos-admin/pkg/toolbox/datax"
)

const TableNameAdminRole = "admin_role"

// AdminRole 管理员角色
type AdminRole struct {
	datax.BaseEntity
	Name       string `gorm:"column:name;type:varchar(32);not null;comment:角色名" json:"name"`                           // 角色名
	GroupId    int64  `gorm:"column:group_id;type:bigint(20);not null;comment:团队id" json:"groupId"`                    // 团队id
	Status     int32  `gorm:"column:status;type:tinyint(4);not null;default:2;comment:角色状态: 1 下线, 2 在线" json:"status"` // 角色状态: 1 下线, 2 在线
	OperatorId int64  `gorm:"column:operator_id;type:bigint(20);not null;comment:操作人id" json:"operatorId"`             // 操作人id
	Deleted    bool   `gorm:"column:deleted;type:tinyint(1);not null;comment:是否删除" json:"deleted"`                     // 是否删除
}

// TableName AdminRole's table name
func (AdminRole) TableName() string {
	return TableNameAdminRole
}
