// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package adminmodel

import (
	"kratos-admin/pkg/toolbox/datax"
)

const TableNameResource = "resource"

// Resource 菜单资源表
type Resource struct {
	datax.BaseEntity
	ParentId   int64  `gorm:"column:parent_id;type:bigint(20);not null;comment:父级资源id" json:"parentId"`                // 父级资源id
	Name       string `gorm:"column:name;type:varchar(64);not null;comment:资源名称" json:"name"`                          // 资源名称
	Type       string `gorm:"column:type;type:varchar(32);not null;comment:资源类型: menu, page, button, api" json:"type"` // 资源类型: menu, page, button, api
	Path       string `gorm:"column:path;type:varchar(512);not null;comment:资源path" json:"path"`                       // 资源path
	Apis       string `gorm:"column:apis;type:json;not null;comment:关联api列表" json:"apis"`                              // 关联api列表
	Weight     int32  `gorm:"column:weight;type:int(11);not null;comment:权重" json:"weight"`                            // 权重
	OperatorId int64  `gorm:"column:operator_id;type:bigint(20);not null;comment:操作人id" json:"operatorId"`             // 操作人id
}

// TableName Resource's table name
func (Resource) TableName() string {
	return TableNameResource
}
