// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-admin/internal/authz"
	"kratos-admin/internal/biz/adminuserbiz"
	"kratos-admin/internal/biz/auditbiz"
	"kratos-admin/internal/biz/permissionbiz"
	"kratos-admin/internal/conf"
	"kratos-admin/internal/data"
	"kratos-admin/internal/data/adminrepo"
	"kratos-admin/internal/server"
	"kratos-admin/internal/service"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, security *conf.Security, permission *conf.Permission, logger log.Logger) (*kratos.App, error) {
	dataData, err := data.NewDataFromConfig(confData)
	if err != nil {
		return nil, err
	}
	operationLogRepo := adminrepo.NewOperationLogRepo(dataData)
	adminUserRepo := adminrepo.NewAdminUserRepo(dataData)
	casbinServer, err := data.NewCasbinServer(confData, dataData)
	if err != nil {
		return nil, err
	}
	store := authz.NewStore(casbinServer)
	adminRoleRepo := adminrepo.NewAdminRoleRepo(dataData, store)
	adminGroupRepo := adminrepo.NewAdminGroupRepo(dataData, store)
	resourceRepo := adminrepo.NewResourceRepo(dataData)
	userPermissionUsecase := permissionbiz.NewUserPermissionUsecase(store, adminUserRepo, adminRoleRepo, adminGroupRepo, resourceRepo, permission)
	adminGroupUsecase := permissionbiz.NewAdminGroupUsecase(adminGroupRepo, resourceRepo, adminUserRepo, adminRoleRepo, permission)
	adminRoleUsecase := permissionbiz.NewAdminRoleUsecase(adminRoleRepo, adminGroupRepo, resourceRepo, adminUserRepo, permission)
	resourceUsecase := permissionbiz.NewResourceUsecase(resourceRepo)
	permissionService := service.NewPermissionService(adminGroupUsecase, adminRoleUsecase, resourceUsecase)
	adminUserUsecase := adminuserbiz.NewAdminUserUsecase(adminUserRepo, adminRoleRepo, adminGroupRepo, userPermissionUsecase)
	loginUsecase := adminuserbiz.NewLoginUsecase(security, adminUserRepo)
	auditUsecase := auditbiz.NewAuditUsecase(operationLogRepo)
	adminUserService := service.NewAdminUserService(adminUserUsecase, loginUsecase, auditUsecase)
	httpServer := server.NewHTTPServer(confServer, security, permission, dataData, operationLogRepo, adminUserRepo, store, userPermissionUsecase, permissionService, adminUserService)
	grpcServer := server.NewGRPCServer(confServer, permissionService, adminUserService)
	app := newApp(logger, httpServer, grpcServer, casbinServer)
	return app, nil
}
