// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: admin/v1/admin_user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminUserGetUserInfo = "/admin.v1.AdminUser/GetUserInfo"
const OperationAdminUserListAdminUser = "/admin.v1.AdminUser/ListAdminUser"
const OperationAdminUserListOperationLog = "/admin.v1.AdminUser/ListOperationLog"
const OperationAdminUserListOptimizer = "/admin.v1.AdminUser/ListOptimizer"
const OperationAdminUserLogin = "/admin.v1.AdminUser/Login"
const OperationAdminUserSaveAdminUser = "/admin.v1.AdminUser/SaveAdminUser"

type AdminUserHTTPServer interface {
	// GetUserInfo 获取登陆用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error)
	// ListAdminUser 获取用户列表
	ListAdminUser(context.Context, *ListAdminUserRequest) (*ListAdminUserReply, error)
	// ListOperationLog 查询审计日志列表
	ListOperationLog(context.Context, *ListOperationLogRequest) (*ListOperationLogReply, error)
	// ListOptimizer 获取优化师列表
	ListOptimizer(context.Context, *ListOptimizerRequest) (*ListOptimizerReply, error)
	// Login 后台账号登陆
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// SaveAdminUser 保存用户
	SaveAdminUser(context.Context, *SaveAdminUserRequest) (*SaveAdminUserReply, error)
}

func RegisterAdminUserHTTPServer(s *http.Server, srv AdminUserHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/user/login", _AdminUser_Login0_HTTP_Handler(srv))
	r.GET("/v1/user/info", _AdminUser_GetUserInfo0_HTTP_Handler(srv))
	r.GET("/v1/user/list", _AdminUser_ListAdminUser0_HTTP_Handler(srv))
	r.POST("/v1/user/save", _AdminUser_SaveAdminUser0_HTTP_Handler(srv))
	r.GET("/v1/optimizer/list", _AdminUser_ListOptimizer0_HTTP_Handler(srv))
	r.GET("v1/operation/log/list", _AdminUser_ListOperationLog0_HTTP_Handler(srv))
}

func _AdminUser_Login0_HTTP_Handler(srv AdminUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUserLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _AdminUser_GetUserInfo0_HTTP_Handler(srv AdminUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUserGetUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserInfo(ctx, req.(*GetUserInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserInfoReply)
		return ctx.Result(200, reply)
	}
}

func _AdminUser_ListAdminUser0_HTTP_Handler(srv AdminUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUserListAdminUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdminUser(ctx, req.(*ListAdminUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminUserReply)
		return ctx.Result(200, reply)
	}
}

func _AdminUser_SaveAdminUser0_HTTP_Handler(srv AdminUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveAdminUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUserSaveAdminUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveAdminUser(ctx, req.(*SaveAdminUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveAdminUserReply)
		return ctx.Result(200, reply)
	}
}

func _AdminUser_ListOptimizer0_HTTP_Handler(srv AdminUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOptimizerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUserListOptimizer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOptimizer(ctx, req.(*ListOptimizerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOptimizerReply)
		return ctx.Result(200, reply)
	}
}

func _AdminUser_ListOperationLog0_HTTP_Handler(srv AdminUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOperationLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminUserListOperationLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOperationLog(ctx, req.(*ListOperationLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOperationLogReply)
		return ctx.Result(200, reply)
	}
}

type AdminUserHTTPClient interface {
	// GetUserInfo 获取登陆用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...http.CallOption) (rsp *GetUserInfoReply, err error)
	// ListAdminUser 获取用户列表
	ListAdminUser(ctx context.Context, req *ListAdminUserRequest, opts ...http.CallOption) (rsp *ListAdminUserReply, err error)
	// ListOperationLog 查询审计日志列表
	ListOperationLog(ctx context.Context, req *ListOperationLogRequest, opts ...http.CallOption) (rsp *ListOperationLogReply, err error)
	// ListOptimizer 获取优化师列表
	ListOptimizer(ctx context.Context, req *ListOptimizerRequest, opts ...http.CallOption) (rsp *ListOptimizerReply, err error)
	// Login 后台账号登陆
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// SaveAdminUser 保存用户
	SaveAdminUser(ctx context.Context, req *SaveAdminUserRequest, opts ...http.CallOption) (rsp *SaveAdminUserReply, err error)
}

type AdminUserHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminUserHTTPClient(client *http.Client) AdminUserHTTPClient {
	return &AdminUserHTTPClientImpl{client}
}

// GetUserInfo 获取登陆用户信息
func (c *AdminUserHTTPClientImpl) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...http.CallOption) (*GetUserInfoReply, error) {
	var out GetUserInfoReply
	pattern := "/v1/user/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminUserGetUserInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAdminUser 获取用户列表
func (c *AdminUserHTTPClientImpl) ListAdminUser(ctx context.Context, in *ListAdminUserRequest, opts ...http.CallOption) (*ListAdminUserReply, error) {
	var out ListAdminUserReply
	pattern := "/v1/user/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminUserListAdminUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListOperationLog 查询审计日志列表
func (c *AdminUserHTTPClientImpl) ListOperationLog(ctx context.Context, in *ListOperationLogRequest, opts ...http.CallOption) (*ListOperationLogReply, error) {
	var out ListOperationLogReply
	pattern := "v1/operation/log/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminUserListOperationLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListOptimizer 获取优化师列表
func (c *AdminUserHTTPClientImpl) ListOptimizer(ctx context.Context, in *ListOptimizerRequest, opts ...http.CallOption) (*ListOptimizerReply, error) {
	var out ListOptimizerReply
	pattern := "/v1/optimizer/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminUserListOptimizer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Login 后台账号登陆
func (c *AdminUserHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUserLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveAdminUser 保存用户
func (c *AdminUserHTTPClientImpl) SaveAdminUser(ctx context.Context, in *SaveAdminUserRequest, opts ...http.CallOption) (*SaveAdminUserReply, error) {
	var out SaveAdminUserReply
	pattern := "/v1/user/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminUserSaveAdminUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
