// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: admin/v1/admin_user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 管理员用户信息
type AdminUserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 用户手机号
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 状态: 1 正常, 2 禁用
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 角色列表
	Roles []*AdminUserInfo_UserRole `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	// 分组列表
	Groups []*AdminUserInfo_UserGroup `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	// 操作人
	Operator      string `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AdminUserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminUserInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AdminUserInfo) GetRoles() []*AdminUserInfo_UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AdminUserInfo) GetGroups() []*AdminUserInfo_UserGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *AdminUserInfo) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// 获取用户列表
type ListAdminUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引
	PageIndex int32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 用户名
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 用户状态
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 团队id
	GroupId int64 `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 角色id
	RoleId        int64 `protobuf:"varint,6,opt,name=roleId,proto3" json:"roleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUserRequest) Reset() {
	*x = ListAdminUserRequest{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUserRequest) ProtoMessage() {}

func (x *ListAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUserRequest.ProtoReflect.Descriptor instead.
func (*ListAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdminUserRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListAdminUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ListAdminUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListAdminUserRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListAdminUserRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ListAdminUserReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户列表
	List []*AdminUserInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页信息
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUserReply) Reset() {
	*x = ListAdminUserReply{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUserReply) ProtoMessage() {}

func (x *ListAdminUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUserReply.ProtoReflect.Descriptor instead.
func (*ListAdminUserReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListAdminUserReply) GetList() []*AdminUserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAdminUserReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 保存用户
type SaveAdminUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 用户手机号
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 状态: 1 正常, 2 禁用
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 角色列表
	RoleIds []int64 `protobuf:"varint,5,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty"`
	// 分组列表
	GroupIds      []int64 `protobuf:"varint,6,rep,packed,name=groupIds,proto3" json:"groupIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAdminUserRequest) Reset() {
	*x = SaveAdminUserRequest{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAdminUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAdminUserRequest) ProtoMessage() {}

func (x *SaveAdminUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAdminUserRequest.ProtoReflect.Descriptor instead.
func (*SaveAdminUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{3}
}

func (x *SaveAdminUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveAdminUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SaveAdminUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SaveAdminUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SaveAdminUserRequest) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *SaveAdminUserRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// 保存用户回复
type SaveAdminUserReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAdminUserReply) Reset() {
	*x = SaveAdminUserReply{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAdminUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAdminUserReply) ProtoMessage() {}

func (x *SaveAdminUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAdminUserReply.ProtoReflect.Descriptor instead.
func (*SaveAdminUserReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{4}
}

func (x *SaveAdminUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取登陆用户信息
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{5}
}

type GetUserInfoReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar   string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 用户权限
	Permissions     *UserPermission `protobuf:"bytes,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	ClosePermission bool            `protobuf:"varint,5,opt,name=closePermission,proto3" json:"closePermission,omitempty"` // 是否关闭权限
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserInfoReply) Reset() {
	*x = GetUserInfoReply{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReply) ProtoMessage() {}

func (x *GetUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserInfoReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoReply) GetPermissions() *UserPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetUserInfoReply) GetClosePermission() bool {
	if x != nil {
		return x.ClosePermission
	}
	return false
}

// 用户权限
type UserPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可访问按钮
	Buttons []string `protobuf:"bytes,1,rep,name=buttons,proto3" json:"buttons,omitempty"`
	// 可访问页面
	Pages         []*UserPermissioPage `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPermission) Reset() {
	*x = UserPermission{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermission) ProtoMessage() {}

func (x *UserPermission) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermission.ProtoReflect.Descriptor instead.
func (*UserPermission) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserPermission) GetButtons() []string {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *UserPermission) GetPages() []*UserPermissioPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

type UserPermissioPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可访问路径
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// 子权限
	Children      []*UserPermissioPage `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPermissioPage) Reset() {
	*x = UserPermissioPage{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermissioPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermissioPage) ProtoMessage() {}

func (x *UserPermissioPage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermissioPage.ProtoReflect.Descriptor instead.
func (*UserPermissioPage) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserPermissioPage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UserPermissioPage) GetChildren() []*UserPermissioPage {
	if x != nil {
		return x.Children
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{9}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{10}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 优化师
type Optimizer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Optimizer) Reset() {
	*x = Optimizer{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Optimizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Optimizer) ProtoMessage() {}

func (x *Optimizer) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Optimizer.ProtoReflect.Descriptor instead.
func (*Optimizer) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{11}
}

func (x *Optimizer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Optimizer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type ListOptimizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptimizerRequest) Reset() {
	*x = ListOptimizerRequest{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptimizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptimizerRequest) ProtoMessage() {}

func (x *ListOptimizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptimizerRequest.ProtoReflect.Descriptor instead.
func (*ListOptimizerRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{12}
}

type ListOptimizerReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户列表
	Users         []*Optimizer `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptimizerReply) Reset() {
	*x = ListOptimizerReply{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptimizerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptimizerReply) ProtoMessage() {}

func (x *ListOptimizerReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptimizerReply.ProtoReflect.Descriptor instead.
func (*ListOptimizerReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{13}
}

func (x *ListOptimizerReply) GetUsers() []*Optimizer {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListOperationLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引
	PageIndex int32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// url
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// method
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// 开始时间
	StartTime int64 `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// 结束时间
	EndTime       int64 `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogRequest) Reset() {
	*x = ListOperationLogRequest{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogRequest) ProtoMessage() {}

func (x *ListOperationLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogRequest.ProtoReflect.Descriptor instead.
func (*ListOperationLogRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{14}
}

func (x *ListOperationLogRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListOperationLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOperationLogRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ListOperationLogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ListOperationLogRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ListOperationLogRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ListOperationLogReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作日志列表
	List []*OperationLog `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页信息
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogReply) Reset() {
	*x = ListOperationLogReply{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogReply) ProtoMessage() {}

func (x *ListOperationLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogReply.ProtoReflect.Descriptor instead.
func (*ListOperationLogReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListOperationLogReply) GetList() []*OperationLog {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOperationLogReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type OperationLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// url
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// operator
	Operator string `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	// method
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// 请求参数
	Params string `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	// 响应内容
	Response string `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	// 请求ip
	Ip string `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 更新时间
	UpdateTime    int64 `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLog) Reset() {
	*x = OperationLog{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLog) ProtoMessage() {}

func (x *OperationLog) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLog.ProtoReflect.Descriptor instead.
func (*OperationLog) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{16}
}

func (x *OperationLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperationLog) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OperationLog) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OperationLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperationLog) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *OperationLog) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *OperationLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OperationLog) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OperationLog) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AdminUserInfo_UserRole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 角色名称
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo_UserRole) Reset() {
	*x = AdminUserInfo_UserRole{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo_UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo_UserRole) ProtoMessage() {}

func (x *AdminUserInfo_UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo_UserRole.ProtoReflect.Descriptor instead.
func (*AdminUserInfo_UserRole) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AdminUserInfo_UserRole) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserInfo_UserRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdminUserInfo_UserGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分组id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 分组名称
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo_UserGroup) Reset() {
	*x = AdminUserInfo_UserGroup{}
	mi := &file_admin_v1_admin_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo_UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo_UserGroup) ProtoMessage() {}

func (x *AdminUserInfo_UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo_UserGroup.ProtoReflect.Descriptor instead.
func (*AdminUserInfo_UserGroup) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_user_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AdminUserInfo_UserGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUserInfo_UserGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_admin_v1_admin_user_proto protoreflect.FileDescriptor

const file_admin_v1_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x19admin/v1/admin_user.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15admin/v1/common.proto\"\xf9\x02\n" +
	"\rAdminUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03R\n" +
	"createTime\x126\n" +
	"\x05roles\x18\x06 \x03(\v2 .admin.v1.AdminUserInfo.UserRoleR\x05roles\x129\n" +
	"\x06groups\x18\a \x03(\v2!.admin.v1.AdminUserInfo.UserGroupR\x06groups\x12\x1a\n" +
	"\boperator\x18\b \x01(\tR\boperator\x1a.\n" +
	"\bUserRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a/\n" +
	"\tUserGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb6\x01\n" +
	"\x14ListAdminUserRequest\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06roleId\x18\x06 \x01(\x03R\x06roleId\"i\n" +
	"\x12ListAdminUserReply\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.admin.v1.AdminUserInfoR\x04list\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.admin.v1.PageInfoR\x04page\"\xa6\x01\n" +
	"\x14SaveAdminUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x18\n" +
	"\aroleIds\x18\x05 \x03(\x03R\aroleIds\x12\x1a\n" +
	"\bgroupIds\x18\x06 \x03(\x03R\bgroupIds\"$\n" +
	"\x12SaveAdminUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12GetUserInfoRequest\"\xbc\x01\n" +
	"\x10GetUserInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12:\n" +
	"\vpermissions\x18\x04 \x01(\v2\x18.admin.v1.UserPermissionR\vpermissions\x12(\n" +
	"\x0fclosePermission\x18\x05 \x01(\bR\x0fclosePermission\"]\n" +
	"\x0eUserPermission\x12\x18\n" +
	"\abuttons\x18\x01 \x03(\tR\abuttons\x121\n" +
	"\x05pages\x18\x02 \x03(\v2\x1b.admin.v1.UserPermissioPageR\x05pages\"`\n" +
	"\x11UserPermissioPage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x127\n" +
	"\bchildren\x18\x02 \x03(\v2\x1b.admin.v1.UserPermissioPageR\bchildren\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\"\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"7\n" +
	"\tOptimizer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"\x16\n" +
	"\x14ListOptimizerRequest\"?\n" +
	"\x12ListOptimizerReply\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.admin.v1.OptimizerR\x05users\"\xb5\x01\n" +
	"\x17ListOperationLogRequest\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\x03R\aendTime\"k\n" +
	"\x15ListOperationLogReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.admin.v1.OperationLogR\x04list\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.admin.v1.PageInfoR\x04page\"\xe8\x01\n" +
	"\fOperationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x05 \x01(\tR\x06params\x12\x1a\n" +
	"\bresponse\x18\x06 \x01(\tR\bresponse\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\t \x01(\x03R\n" +
	"updateTime2\xee\x04\n" +
	"\tAdminUser\x12P\n" +
	"\x05Login\x12\x16.admin.v1.LoginRequest\x1a\x14.admin.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/user/login\x12^\n" +
	"\vGetUserInfo\x12\x1c.admin.v1.GetUserInfoRequest\x1a\x1a.admin.v1.GetUserInfoReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/info\x12d\n" +
	"\rListAdminUser\x12\x1e.admin.v1.ListAdminUserRequest\x1a\x1c.admin.v1.ListAdminUserReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/list\x12g\n" +
	"\rSaveAdminUser\x12\x1e.admin.v1.SaveAdminUserRequest\x1a\x1c.admin.v1.SaveAdminUserReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/user/save\x12i\n" +
	"\rListOptimizer\x12\x1e.admin.v1.ListOptimizerRequest\x1a\x1c.admin.v1.ListOptimizerReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/optimizer/list\x12u\n" +
	"\x10ListOperationLog\x12!.admin.v1.ListOperationLogRequest\x1a\x1f.admin.v1.ListOperationLogReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15v1/operation/log/listB\x1dZ\x1bkratos-admin/pb/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_admin_user_proto_rawDescOnce sync.Once
	file_admin_v1_admin_user_proto_rawDescData []byte
)

func file_admin_v1_admin_user_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_user_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_user_proto_rawDesc), len(file_admin_v1_admin_user_proto_rawDesc)))
	})
	return file_admin_v1_admin_user_proto_rawDescData
}

var file_admin_v1_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_admin_v1_admin_user_proto_goTypes = []any{
	(*AdminUserInfo)(nil),           // 0: admin.v1.AdminUserInfo
	(*ListAdminUserRequest)(nil),    // 1: admin.v1.ListAdminUserRequest
	(*ListAdminUserReply)(nil),      // 2: admin.v1.ListAdminUserReply
	(*SaveAdminUserRequest)(nil),    // 3: admin.v1.SaveAdminUserRequest
	(*SaveAdminUserReply)(nil),      // 4: admin.v1.SaveAdminUserReply
	(*GetUserInfoRequest)(nil),      // 5: admin.v1.GetUserInfoRequest
	(*GetUserInfoReply)(nil),        // 6: admin.v1.GetUserInfoReply
	(*UserPermission)(nil),          // 7: admin.v1.UserPermission
	(*UserPermissioPage)(nil),       // 8: admin.v1.UserPermissioPage
	(*LoginRequest)(nil),            // 9: admin.v1.LoginRequest
	(*LoginReply)(nil),              // 10: admin.v1.LoginReply
	(*Optimizer)(nil),               // 11: admin.v1.Optimizer
	(*ListOptimizerRequest)(nil),    // 12: admin.v1.ListOptimizerRequest
	(*ListOptimizerReply)(nil),      // 13: admin.v1.ListOptimizerReply
	(*ListOperationLogRequest)(nil), // 14: admin.v1.ListOperationLogRequest
	(*ListOperationLogReply)(nil),   // 15: admin.v1.ListOperationLogReply
	(*OperationLog)(nil),            // 16: admin.v1.OperationLog
	(*AdminUserInfo_UserRole)(nil),  // 17: admin.v1.AdminUserInfo.UserRole
	(*AdminUserInfo_UserGroup)(nil), // 18: admin.v1.AdminUserInfo.UserGroup
	(*PageInfo)(nil),                // 19: admin.v1.PageInfo
}
var file_admin_v1_admin_user_proto_depIdxs = []int32{
	17, // 0: admin.v1.AdminUserInfo.roles:type_name -> admin.v1.AdminUserInfo.UserRole
	18, // 1: admin.v1.AdminUserInfo.groups:type_name -> admin.v1.AdminUserInfo.UserGroup
	0,  // 2: admin.v1.ListAdminUserReply.list:type_name -> admin.v1.AdminUserInfo
	19, // 3: admin.v1.ListAdminUserReply.page:type_name -> admin.v1.PageInfo
	7,  // 4: admin.v1.GetUserInfoReply.permissions:type_name -> admin.v1.UserPermission
	8,  // 5: admin.v1.UserPermission.pages:type_name -> admin.v1.UserPermissioPage
	8,  // 6: admin.v1.UserPermissioPage.children:type_name -> admin.v1.UserPermissioPage
	11, // 7: admin.v1.ListOptimizerReply.users:type_name -> admin.v1.Optimizer
	16, // 8: admin.v1.ListOperationLogReply.list:type_name -> admin.v1.OperationLog
	19, // 9: admin.v1.ListOperationLogReply.page:type_name -> admin.v1.PageInfo
	9,  // 10: admin.v1.AdminUser.Login:input_type -> admin.v1.LoginRequest
	5,  // 11: admin.v1.AdminUser.GetUserInfo:input_type -> admin.v1.GetUserInfoRequest
	1,  // 12: admin.v1.AdminUser.ListAdminUser:input_type -> admin.v1.ListAdminUserRequest
	3,  // 13: admin.v1.AdminUser.SaveAdminUser:input_type -> admin.v1.SaveAdminUserRequest
	12, // 14: admin.v1.AdminUser.ListOptimizer:input_type -> admin.v1.ListOptimizerRequest
	14, // 15: admin.v1.AdminUser.ListOperationLog:input_type -> admin.v1.ListOperationLogRequest
	10, // 16: admin.v1.AdminUser.Login:output_type -> admin.v1.LoginReply
	6,  // 17: admin.v1.AdminUser.GetUserInfo:output_type -> admin.v1.GetUserInfoReply
	2,  // 18: admin.v1.AdminUser.ListAdminUser:output_type -> admin.v1.ListAdminUserReply
	4,  // 19: admin.v1.AdminUser.SaveAdminUser:output_type -> admin.v1.SaveAdminUserReply
	13, // 20: admin.v1.AdminUser.ListOptimizer:output_type -> admin.v1.ListOptimizerReply
	15, // 21: admin.v1.AdminUser.ListOperationLog:output_type -> admin.v1.ListOperationLogReply
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_user_proto_init() }
func file_admin_v1_admin_user_proto_init() {
	if File_admin_v1_admin_user_proto != nil {
		return
	}
	file_admin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_user_proto_rawDesc), len(file_admin_v1_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_user_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_user_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_user_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_user_proto = out.File
	file_admin_v1_admin_user_proto_goTypes = nil
	file_admin_v1_admin_user_proto_depIdxs = nil
}
