// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/admin_user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AdminUserInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AdminUserInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminUserInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AdminUserInfoMultiError, or
// nil if none found.
func (m *AdminUserInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminUserInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Nickname

	// no validation rules for Phone

	// no validation rules for Status

	// no validation rules for CreateTime

	for idx, item := range m.GetRoles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AdminUserInfoValidationError{
						field:  fmt.Sprintf("Roles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AdminUserInfoValidationError{
						field:  fmt.Sprintf("Roles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AdminUserInfoValidationError{
					field:  fmt.Sprintf("Roles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetGroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AdminUserInfoValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AdminUserInfoValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AdminUserInfoValidationError{
					field:  fmt.Sprintf("Groups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Operator

	if len(errors) > 0 {
		return AdminUserInfoMultiError(errors)
	}

	return nil
}

// AdminUserInfoMultiError is an error wrapping multiple validation errors
// returned by AdminUserInfo.ValidateAll() if the designated constraints
// aren't met.
type AdminUserInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminUserInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminUserInfoMultiError) AllErrors() []error { return m }

// AdminUserInfoValidationError is the validation error returned by
// AdminUserInfo.Validate if the designated constraints aren't met.
type AdminUserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminUserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminUserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminUserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminUserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminUserInfoValidationError) ErrorName() string { return "AdminUserInfoValidationError" }

// Error satisfies the builtin error interface
func (e AdminUserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminUserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminUserInfoValidationError{}

// Validate checks the field values on ListAdminUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAdminUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAdminUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAdminUserRequestMultiError, or nil if none found.
func (m *ListAdminUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAdminUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageIndex

	// no validation rules for PageSize

	// no validation rules for Nickname

	// no validation rules for Status

	// no validation rules for GroupId

	// no validation rules for RoleId

	if len(errors) > 0 {
		return ListAdminUserRequestMultiError(errors)
	}

	return nil
}

// ListAdminUserRequestMultiError is an error wrapping multiple validation
// errors returned by ListAdminUserRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAdminUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAdminUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAdminUserRequestMultiError) AllErrors() []error { return m }

// ListAdminUserRequestValidationError is the validation error returned by
// ListAdminUserRequest.Validate if the designated constraints aren't met.
type ListAdminUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAdminUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAdminUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAdminUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAdminUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAdminUserRequestValidationError) ErrorName() string {
	return "ListAdminUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAdminUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAdminUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAdminUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAdminUserRequestValidationError{}

// Validate checks the field values on ListAdminUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAdminUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAdminUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAdminUserReplyMultiError, or nil if none found.
func (m *ListAdminUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAdminUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAdminUserReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAdminUserReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAdminUserReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListAdminUserReplyValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListAdminUserReplyValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListAdminUserReplyValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListAdminUserReplyMultiError(errors)
	}

	return nil
}

// ListAdminUserReplyMultiError is an error wrapping multiple validation errors
// returned by ListAdminUserReply.ValidateAll() if the designated constraints
// aren't met.
type ListAdminUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAdminUserReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAdminUserReplyMultiError) AllErrors() []error { return m }

// ListAdminUserReplyValidationError is the validation error returned by
// ListAdminUserReply.Validate if the designated constraints aren't met.
type ListAdminUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAdminUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAdminUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAdminUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAdminUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAdminUserReplyValidationError) ErrorName() string {
	return "ListAdminUserReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListAdminUserReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAdminUserReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAdminUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAdminUserReplyValidationError{}

// Validate checks the field values on SaveAdminUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SaveAdminUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SaveAdminUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SaveAdminUserRequestMultiError, or nil if none found.
func (m *SaveAdminUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SaveAdminUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Nickname

	// no validation rules for Phone

	// no validation rules for Status

	if len(errors) > 0 {
		return SaveAdminUserRequestMultiError(errors)
	}

	return nil
}

// SaveAdminUserRequestMultiError is an error wrapping multiple validation
// errors returned by SaveAdminUserRequest.ValidateAll() if the designated
// constraints aren't met.
type SaveAdminUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SaveAdminUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SaveAdminUserRequestMultiError) AllErrors() []error { return m }

// SaveAdminUserRequestValidationError is the validation error returned by
// SaveAdminUserRequest.Validate if the designated constraints aren't met.
type SaveAdminUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SaveAdminUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SaveAdminUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SaveAdminUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SaveAdminUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SaveAdminUserRequestValidationError) ErrorName() string {
	return "SaveAdminUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SaveAdminUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSaveAdminUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SaveAdminUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SaveAdminUserRequestValidationError{}

// Validate checks the field values on SaveAdminUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SaveAdminUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SaveAdminUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SaveAdminUserReplyMultiError, or nil if none found.
func (m *SaveAdminUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SaveAdminUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SaveAdminUserReplyMultiError(errors)
	}

	return nil
}

// SaveAdminUserReplyMultiError is an error wrapping multiple validation errors
// returned by SaveAdminUserReply.ValidateAll() if the designated constraints
// aren't met.
type SaveAdminUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SaveAdminUserReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SaveAdminUserReplyMultiError) AllErrors() []error { return m }

// SaveAdminUserReplyValidationError is the validation error returned by
// SaveAdminUserReply.Validate if the designated constraints aren't met.
type SaveAdminUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SaveAdminUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SaveAdminUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SaveAdminUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SaveAdminUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SaveAdminUserReplyValidationError) ErrorName() string {
	return "SaveAdminUserReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SaveAdminUserReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSaveAdminUserReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SaveAdminUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SaveAdminUserReplyValidationError{}

// Validate checks the field values on GetUserInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserInfoRequestMultiError, or nil if none found.
func (m *GetUserInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserInfoRequestMultiError(errors)
	}

	return nil
}

// GetUserInfoRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserInfoRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserInfoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserInfoRequestMultiError) AllErrors() []error { return m }

// GetUserInfoRequestValidationError is the validation error returned by
// GetUserInfoRequest.Validate if the designated constraints aren't met.
type GetUserInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserInfoRequestValidationError) ErrorName() string {
	return "GetUserInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserInfoRequestValidationError{}

// Validate checks the field values on GetUserInfoReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserInfoReplyMultiError, or nil if none found.
func (m *GetUserInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Nickname

	// no validation rules for Avatar

	if all {
		switch v := interface{}(m.GetPermissions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserInfoReplyValidationError{
					field:  "Permissions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserInfoReplyValidationError{
					field:  "Permissions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPermissions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserInfoReplyValidationError{
				field:  "Permissions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ClosePermission

	if len(errors) > 0 {
		return GetUserInfoReplyMultiError(errors)
	}

	return nil
}

// GetUserInfoReplyMultiError is an error wrapping multiple validation errors
// returned by GetUserInfoReply.ValidateAll() if the designated constraints
// aren't met.
type GetUserInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserInfoReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserInfoReplyMultiError) AllErrors() []error { return m }

// GetUserInfoReplyValidationError is the validation error returned by
// GetUserInfoReply.Validate if the designated constraints aren't met.
type GetUserInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserInfoReplyValidationError) ErrorName() string { return "GetUserInfoReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetUserInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserInfoReplyValidationError{}

// Validate checks the field values on UserPermission with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserPermission) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserPermission with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserPermissionMultiError,
// or nil if none found.
func (m *UserPermission) ValidateAll() error {
	return m.validate(true)
}

func (m *UserPermission) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserPermissionValidationError{
						field:  fmt.Sprintf("Pages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserPermissionValidationError{
						field:  fmt.Sprintf("Pages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserPermissionValidationError{
					field:  fmt.Sprintf("Pages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserPermissionMultiError(errors)
	}

	return nil
}

// UserPermissionMultiError is an error wrapping multiple validation errors
// returned by UserPermission.ValidateAll() if the designated constraints
// aren't met.
type UserPermissionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserPermissionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserPermissionMultiError) AllErrors() []error { return m }

// UserPermissionValidationError is the validation error returned by
// UserPermission.Validate if the designated constraints aren't met.
type UserPermissionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserPermissionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserPermissionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserPermissionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserPermissionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserPermissionValidationError) ErrorName() string { return "UserPermissionValidationError" }

// Error satisfies the builtin error interface
func (e UserPermissionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserPermission.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserPermissionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserPermissionValidationError{}

// Validate checks the field values on UserPermissioPage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserPermissioPage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserPermissioPage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserPermissioPageMultiError, or nil if none found.
func (m *UserPermissioPage) ValidateAll() error {
	return m.validate(true)
}

func (m *UserPermissioPage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Path

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserPermissioPageValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserPermissioPageValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserPermissioPageValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserPermissioPageMultiError(errors)
	}

	return nil
}

// UserPermissioPageMultiError is an error wrapping multiple validation errors
// returned by UserPermissioPage.ValidateAll() if the designated constraints
// aren't met.
type UserPermissioPageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserPermissioPageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserPermissioPageMultiError) AllErrors() []error { return m }

// UserPermissioPageValidationError is the validation error returned by
// UserPermissioPage.Validate if the designated constraints aren't met.
type UserPermissioPageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserPermissioPageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserPermissioPageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserPermissioPageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserPermissioPageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserPermissioPageValidationError) ErrorName() string {
	return "UserPermissioPageValidationError"
}

// Error satisfies the builtin error interface
func (e UserPermissioPageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserPermissioPage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserPermissioPageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserPermissioPageValidationError{}

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginRequestMultiError, or
// nil if none found.
func (m *LoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Password

	if len(errors) > 0 {
		return LoginRequestMultiError(errors)
	}

	return nil
}

// LoginRequestMultiError is an error wrapping multiple validation errors
// returned by LoginRequest.ValidateAll() if the designated constraints aren't met.
type LoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginRequestMultiError) AllErrors() []error { return m }

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

// Validate checks the field values on LoginReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginReplyMultiError, or
// nil if none found.
func (m *LoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return LoginReplyMultiError(errors)
	}

	return nil
}

// LoginReplyMultiError is an error wrapping multiple validation errors
// returned by LoginReply.ValidateAll() if the designated constraints aren't met.
type LoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginReplyMultiError) AllErrors() []error { return m }

// LoginReplyValidationError is the validation error returned by
// LoginReply.Validate if the designated constraints aren't met.
type LoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginReplyValidationError) ErrorName() string { return "LoginReplyValidationError" }

// Error satisfies the builtin error interface
func (e LoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginReplyValidationError{}

// Validate checks the field values on LogoutRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogoutRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogoutRequestMultiError, or
// nil if none found.
func (m *LogoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LogoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LogoutRequestMultiError(errors)
	}

	return nil
}

// LogoutRequestMultiError is an error wrapping multiple validation errors
// returned by LogoutRequest.ValidateAll() if the designated constraints
// aren't met.
type LogoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogoutRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogoutRequestMultiError) AllErrors() []error { return m }

// LogoutRequestValidationError is the validation error returned by
// LogoutRequest.Validate if the designated constraints aren't met.
type LogoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogoutRequestValidationError) ErrorName() string { return "LogoutRequestValidationError" }

// Error satisfies the builtin error interface
func (e LogoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogoutRequestValidationError{}

// Validate checks the field values on LogoutReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogoutReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogoutReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogoutReplyMultiError, or
// nil if none found.
func (m *LogoutReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LogoutReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LogoutReplyMultiError(errors)
	}

	return nil
}

// LogoutReplyMultiError is an error wrapping multiple validation errors
// returned by LogoutReply.ValidateAll() if the designated constraints aren't met.
type LogoutReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogoutReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogoutReplyMultiError) AllErrors() []error { return m }

// LogoutReplyValidationError is the validation error returned by
// LogoutReply.Validate if the designated constraints aren't met.
type LogoutReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogoutReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogoutReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogoutReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogoutReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogoutReplyValidationError) ErrorName() string { return "LogoutReplyValidationError" }

// Error satisfies the builtin error interface
func (e LogoutReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogoutReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogoutReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogoutReplyValidationError{}

// Validate checks the field values on Optimizer with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Optimizer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Optimizer with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OptimizerMultiError, or nil
// if none found.
func (m *Optimizer) ValidateAll() error {
	return m.validate(true)
}

func (m *Optimizer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Nickname

	if len(errors) > 0 {
		return OptimizerMultiError(errors)
	}

	return nil
}

// OptimizerMultiError is an error wrapping multiple validation errors returned
// by Optimizer.ValidateAll() if the designated constraints aren't met.
type OptimizerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OptimizerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OptimizerMultiError) AllErrors() []error { return m }

// OptimizerValidationError is the validation error returned by
// Optimizer.Validate if the designated constraints aren't met.
type OptimizerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OptimizerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OptimizerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OptimizerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OptimizerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OptimizerValidationError) ErrorName() string { return "OptimizerValidationError" }

// Error satisfies the builtin error interface
func (e OptimizerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOptimizer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OptimizerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OptimizerValidationError{}

// Validate checks the field values on ListOptimizerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOptimizerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOptimizerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOptimizerRequestMultiError, or nil if none found.
func (m *ListOptimizerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOptimizerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListOptimizerRequestMultiError(errors)
	}

	return nil
}

// ListOptimizerRequestMultiError is an error wrapping multiple validation
// errors returned by ListOptimizerRequest.ValidateAll() if the designated
// constraints aren't met.
type ListOptimizerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOptimizerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOptimizerRequestMultiError) AllErrors() []error { return m }

// ListOptimizerRequestValidationError is the validation error returned by
// ListOptimizerRequest.Validate if the designated constraints aren't met.
type ListOptimizerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOptimizerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOptimizerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOptimizerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOptimizerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOptimizerRequestValidationError) ErrorName() string {
	return "ListOptimizerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOptimizerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOptimizerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOptimizerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOptimizerRequestValidationError{}

// Validate checks the field values on ListOptimizerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOptimizerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOptimizerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOptimizerReplyMultiError, or nil if none found.
func (m *ListOptimizerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOptimizerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetUsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListOptimizerReplyValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListOptimizerReplyValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListOptimizerReplyValidationError{
					field:  fmt.Sprintf("Users[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListOptimizerReplyMultiError(errors)
	}

	return nil
}

// ListOptimizerReplyMultiError is an error wrapping multiple validation errors
// returned by ListOptimizerReply.ValidateAll() if the designated constraints
// aren't met.
type ListOptimizerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOptimizerReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOptimizerReplyMultiError) AllErrors() []error { return m }

// ListOptimizerReplyValidationError is the validation error returned by
// ListOptimizerReply.Validate if the designated constraints aren't met.
type ListOptimizerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOptimizerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOptimizerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOptimizerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOptimizerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOptimizerReplyValidationError) ErrorName() string {
	return "ListOptimizerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListOptimizerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOptimizerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOptimizerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOptimizerReplyValidationError{}

// Validate checks the field values on ListOperationLogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOperationLogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOperationLogRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOperationLogRequestMultiError, or nil if none found.
func (m *ListOperationLogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOperationLogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageIndex

	// no validation rules for PageSize

	// no validation rules for Url

	// no validation rules for Method

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return ListOperationLogRequestMultiError(errors)
	}

	return nil
}

// ListOperationLogRequestMultiError is an error wrapping multiple validation
// errors returned by ListOperationLogRequest.ValidateAll() if the designated
// constraints aren't met.
type ListOperationLogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOperationLogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOperationLogRequestMultiError) AllErrors() []error { return m }

// ListOperationLogRequestValidationError is the validation error returned by
// ListOperationLogRequest.Validate if the designated constraints aren't met.
type ListOperationLogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOperationLogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOperationLogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOperationLogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOperationLogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOperationLogRequestValidationError) ErrorName() string {
	return "ListOperationLogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOperationLogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOperationLogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOperationLogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOperationLogRequestValidationError{}

// Validate checks the field values on ListOperationLogReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOperationLogReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOperationLogReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOperationLogReplyMultiError, or nil if none found.
func (m *ListOperationLogReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOperationLogReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListOperationLogReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListOperationLogReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListOperationLogReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListOperationLogReplyValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListOperationLogReplyValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListOperationLogReplyValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListOperationLogReplyMultiError(errors)
	}

	return nil
}

// ListOperationLogReplyMultiError is an error wrapping multiple validation
// errors returned by ListOperationLogReply.ValidateAll() if the designated
// constraints aren't met.
type ListOperationLogReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOperationLogReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOperationLogReplyMultiError) AllErrors() []error { return m }

// ListOperationLogReplyValidationError is the validation error returned by
// ListOperationLogReply.Validate if the designated constraints aren't met.
type ListOperationLogReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOperationLogReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOperationLogReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOperationLogReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOperationLogReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOperationLogReplyValidationError) ErrorName() string {
	return "ListOperationLogReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListOperationLogReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOperationLogReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOperationLogReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOperationLogReplyValidationError{}

// Validate checks the field values on OperationLog with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OperationLog) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OperationLog with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OperationLogMultiError, or
// nil if none found.
func (m *OperationLog) ValidateAll() error {
	return m.validate(true)
}

func (m *OperationLog) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Url

	// no validation rules for Operator

	// no validation rules for Method

	// no validation rules for Params

	// no validation rules for Response

	// no validation rules for Ip

	// no validation rules for CreateTime

	// no validation rules for UpdateTime

	if len(errors) > 0 {
		return OperationLogMultiError(errors)
	}

	return nil
}

// OperationLogMultiError is an error wrapping multiple validation errors
// returned by OperationLog.ValidateAll() if the designated constraints aren't met.
type OperationLogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OperationLogMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OperationLogMultiError) AllErrors() []error { return m }

// OperationLogValidationError is the validation error returned by
// OperationLog.Validate if the designated constraints aren't met.
type OperationLogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OperationLogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OperationLogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OperationLogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OperationLogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OperationLogValidationError) ErrorName() string { return "OperationLogValidationError" }

// Error satisfies the builtin error interface
func (e OperationLogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOperationLog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OperationLogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OperationLogValidationError{}

// Validate checks the field values on AdminUserInfo_UserRole with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdminUserInfo_UserRole) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminUserInfo_UserRole with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminUserInfo_UserRoleMultiError, or nil if none found.
func (m *AdminUserInfo_UserRole) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminUserInfo_UserRole) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return AdminUserInfo_UserRoleMultiError(errors)
	}

	return nil
}

// AdminUserInfo_UserRoleMultiError is an error wrapping multiple validation
// errors returned by AdminUserInfo_UserRole.ValidateAll() if the designated
// constraints aren't met.
type AdminUserInfo_UserRoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminUserInfo_UserRoleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminUserInfo_UserRoleMultiError) AllErrors() []error { return m }

// AdminUserInfo_UserRoleValidationError is the validation error returned by
// AdminUserInfo_UserRole.Validate if the designated constraints aren't met.
type AdminUserInfo_UserRoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminUserInfo_UserRoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminUserInfo_UserRoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminUserInfo_UserRoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminUserInfo_UserRoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminUserInfo_UserRoleValidationError) ErrorName() string {
	return "AdminUserInfo_UserRoleValidationError"
}

// Error satisfies the builtin error interface
func (e AdminUserInfo_UserRoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminUserInfo_UserRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminUserInfo_UserRoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminUserInfo_UserRoleValidationError{}

// Validate checks the field values on AdminUserInfo_UserGroup with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdminUserInfo_UserGroup) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminUserInfo_UserGroup with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminUserInfo_UserGroupMultiError, or nil if none found.
func (m *AdminUserInfo_UserGroup) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminUserInfo_UserGroup) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return AdminUserInfo_UserGroupMultiError(errors)
	}

	return nil
}

// AdminUserInfo_UserGroupMultiError is an error wrapping multiple validation
// errors returned by AdminUserInfo_UserGroup.ValidateAll() if the designated
// constraints aren't met.
type AdminUserInfo_UserGroupMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminUserInfo_UserGroupMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminUserInfo_UserGroupMultiError) AllErrors() []error { return m }

// AdminUserInfo_UserGroupValidationError is the validation error returned by
// AdminUserInfo_UserGroup.Validate if the designated constraints aren't met.
type AdminUserInfo_UserGroupValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminUserInfo_UserGroupValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminUserInfo_UserGroupValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminUserInfo_UserGroupValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminUserInfo_UserGroupValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminUserInfo_UserGroupValidationError) ErrorName() string {
	return "AdminUserInfo_UserGroupValidationError"
}

// Error satisfies the builtin error interface
func (e AdminUserInfo_UserGroupValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminUserInfo_UserGroup.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminUserInfo_UserGroupValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminUserInfo_UserGroupValidationError{}
