// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: admin/v1/admin_user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminUser_Login_FullMethodName            = "/admin.v1.AdminUser/Login"
	AdminUser_GetUserInfo_FullMethodName      = "/admin.v1.AdminUser/GetUserInfo"
	AdminUser_ListAdminUser_FullMethodName    = "/admin.v1.AdminUser/ListAdminUser"
	AdminUser_SaveAdminUser_FullMethodName    = "/admin.v1.AdminUser/SaveAdminUser"
	AdminUser_ListOptimizer_FullMethodName    = "/admin.v1.AdminUser/ListOptimizer"
	AdminUser_ListOperationLog_FullMethodName = "/admin.v1.AdminUser/ListOperationLog"
)

// AdminUserClient is the client API for AdminUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 后台账号管理
type AdminUserClient interface {
	// 后台账号登陆
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// 获取登陆用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error)
	// 获取用户列表
	ListAdminUser(ctx context.Context, in *ListAdminUserRequest, opts ...grpc.CallOption) (*ListAdminUserReply, error)
	// 保存用户
	SaveAdminUser(ctx context.Context, in *SaveAdminUserRequest, opts ...grpc.CallOption) (*SaveAdminUserReply, error)
	// 获取优化师列表
	ListOptimizer(ctx context.Context, in *ListOptimizerRequest, opts ...grpc.CallOption) (*ListOptimizerReply, error)
	// 查询审计日志列表
	ListOperationLog(ctx context.Context, in *ListOperationLogRequest, opts ...grpc.CallOption) (*ListOperationLogReply, error)
}

type adminUserClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminUserClient(cc grpc.ClientConnInterface) AdminUserClient {
	return &adminUserClient{cc}
}

func (c *adminUserClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, AdminUser_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoReply)
	err := c.cc.Invoke(ctx, AdminUser_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) ListAdminUser(ctx context.Context, in *ListAdminUserRequest, opts ...grpc.CallOption) (*ListAdminUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUserReply)
	err := c.cc.Invoke(ctx, AdminUser_ListAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) SaveAdminUser(ctx context.Context, in *SaveAdminUserRequest, opts ...grpc.CallOption) (*SaveAdminUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAdminUserReply)
	err := c.cc.Invoke(ctx, AdminUser_SaveAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) ListOptimizer(ctx context.Context, in *ListOptimizerRequest, opts ...grpc.CallOption) (*ListOptimizerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOptimizerReply)
	err := c.cc.Invoke(ctx, AdminUser_ListOptimizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserClient) ListOperationLog(ctx context.Context, in *ListOperationLogRequest, opts ...grpc.CallOption) (*ListOperationLogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperationLogReply)
	err := c.cc.Invoke(ctx, AdminUser_ListOperationLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminUserServer is the server API for AdminUser service.
// All implementations must embed UnimplementedAdminUserServer
// for forward compatibility.
//
// 后台账号管理
type AdminUserServer interface {
	// 后台账号登陆
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// 获取登陆用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error)
	// 获取用户列表
	ListAdminUser(context.Context, *ListAdminUserRequest) (*ListAdminUserReply, error)
	// 保存用户
	SaveAdminUser(context.Context, *SaveAdminUserRequest) (*SaveAdminUserReply, error)
	// 获取优化师列表
	ListOptimizer(context.Context, *ListOptimizerRequest) (*ListOptimizerReply, error)
	// 查询审计日志列表
	ListOperationLog(context.Context, *ListOperationLogRequest) (*ListOperationLogReply, error)
	mustEmbedUnimplementedAdminUserServer()
}

// UnimplementedAdminUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminUserServer struct{}

func (UnimplementedAdminUserServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminUserServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAdminUserServer) ListAdminUser(context.Context, *ListAdminUserRequest) (*ListAdminUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUser not implemented")
}
func (UnimplementedAdminUserServer) SaveAdminUser(context.Context, *SaveAdminUserRequest) (*SaveAdminUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAdminUser not implemented")
}
func (UnimplementedAdminUserServer) ListOptimizer(context.Context, *ListOptimizerRequest) (*ListOptimizerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOptimizer not implemented")
}
func (UnimplementedAdminUserServer) ListOperationLog(context.Context, *ListOperationLogRequest) (*ListOperationLogReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperationLog not implemented")
}
func (UnimplementedAdminUserServer) mustEmbedUnimplementedAdminUserServer() {}
func (UnimplementedAdminUserServer) testEmbeddedByValue()                   {}

// UnsafeAdminUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminUserServer will
// result in compilation errors.
type UnsafeAdminUserServer interface {
	mustEmbedUnimplementedAdminUserServer()
}

func RegisterAdminUserServer(s grpc.ServiceRegistrar, srv AdminUserServer) {
	// If the following call panics, it indicates UnimplementedAdminUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminUser_ServiceDesc, srv)
}

func _AdminUser_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_ListAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).ListAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_ListAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).ListAdminUser(ctx, req.(*ListAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_SaveAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).SaveAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_SaveAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).SaveAdminUser(ctx, req.(*SaveAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_ListOptimizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOptimizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).ListOptimizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_ListOptimizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).ListOptimizer(ctx, req.(*ListOptimizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUser_ListOperationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServer).ListOperationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUser_ListOperationLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServer).ListOperationLog(ctx, req.(*ListOperationLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminUser_ServiceDesc is the grpc.ServiceDesc for AdminUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminUser",
	HandlerType: (*AdminUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminUser_Login_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _AdminUser_GetUserInfo_Handler,
		},
		{
			MethodName: "ListAdminUser",
			Handler:    _AdminUser_ListAdminUser_Handler,
		},
		{
			MethodName: "SaveAdminUser",
			Handler:    _AdminUser_SaveAdminUser_Handler,
		},
		{
			MethodName: "ListOptimizer",
			Handler:    _AdminUser_ListOptimizer_Handler,
		},
		{
			MethodName: "ListOperationLog",
			Handler:    _AdminUser_ListOperationLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/admin_user.proto",
}
