// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: admin/v1/common.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引，必须大于等于 0
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// 每页大小，必须大于等于 0
	Size          int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageOption) Reset() {
	*x = PageOption{}
	mi := &file_admin_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageOption) ProtoMessage() {}

func (x *PageOption) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageOption.ProtoReflect.Descriptor instead.
func (*PageOption) Descriptor() ([]byte, []int) {
	return file_admin_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *PageOption) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PageOption) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前分页
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// 每页条数
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// 下一页参数
	Next string `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// 总条数
	Total int32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	// 是否结束
	IsEnd         bool `protobuf:"varint,5,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_admin_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PageInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageInfo) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *PageInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageInfo) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_admin_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_common_proto_rawDescGZIP(), []int{2}
}

// 分群分组信息
type SegmentGroupItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分群ID
	SegmentId int64 `protobuf:"varint,1,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
	// 分群权重
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// 分组名称
	GroupId       int64 `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentGroupItem) Reset() {
	*x = SegmentGroupItem{}
	mi := &file_admin_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentGroupItem) ProtoMessage() {}

func (x *SegmentGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentGroupItem.ProtoReflect.Descriptor instead.
func (*SegmentGroupItem) Descriptor() ([]byte, []int) {
	return file_admin_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentGroupItem) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *SegmentGroupItem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SegmentGroupItem) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 分群分组信息
type SegmentGroupInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分群ID
	SegmentId int64 `protobuf:"varint,1,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
	// 分群权重
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// 分组ID
	GroupId int64 `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 分群名称
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 分组名称
	GroupName     string `protobuf:"bytes,5,opt,name=groupName,proto3" json:"groupName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentGroupInfo) Reset() {
	*x = SegmentGroupInfo{}
	mi := &file_admin_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentGroupInfo) ProtoMessage() {}

func (x *SegmentGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentGroupInfo.ProtoReflect.Descriptor instead.
func (*SegmentGroupInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentGroupInfo) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *SegmentGroupInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SegmentGroupInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SegmentGroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SegmentGroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// 用户余额信息
type UserBalance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 金币数
	Coin int32 `protobuf:"varint,1,opt,name=coin,proto3" json:"coin,omitempty"`
	// 赠币数
	Bonus int32 `protobuf:"varint,2,opt,name=bonus,proto3" json:"bonus,omitempty"`
	// 总币数
	TotalCoins    int32 `protobuf:"varint,3,opt,name=totalCoins,proto3" json:"totalCoins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalance) Reset() {
	*x = UserBalance{}
	mi := &file_admin_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalance) ProtoMessage() {}

func (x *UserBalance) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalance.ProtoReflect.Descriptor instead.
func (*UserBalance) Descriptor() ([]byte, []int) {
	return file_admin_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *UserBalance) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *UserBalance) GetBonus() int32 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *UserBalance) GetTotalCoins() int32 {
	if x != nil {
		return x.TotalCoins
	}
	return 0
}

var File_admin_v1_common_proto protoreflect.FileDescriptor

const file_admin_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15admin/v1/common.proto\x12\badmin.v1\x1a\x17validate/validate.proto\"H\n" +
	"\n" +
	"PageOption\x12\x1d\n" +
	"\x05index\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x05index\x12\x1b\n" +
	"\x04size\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x04size\"t\n" +
	"\bPageInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04next\x18\x03 \x01(\tR\x04next\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x14\n" +
	"\x05isEnd\x18\x05 \x01(\bR\x05isEnd\"\f\n" +
	"\n" +
	"EmptyReply\"b\n" +
	"\x10SegmentGroupItem\x12\x1c\n" +
	"\tsegmentId\x18\x01 \x01(\x03R\tsegmentId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x03R\agroupId\"\x94\x01\n" +
	"\x10SegmentGroupInfo\x12\x1c\n" +
	"\tsegmentId\x18\x01 \x01(\x03R\tsegmentId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tgroupName\x18\x05 \x01(\tR\tgroupName\"W\n" +
	"\vUserBalance\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\x05R\x04coin\x12\x14\n" +
	"\x05bonus\x18\x02 \x01(\x05R\x05bonus\x12\x1e\n" +
	"\n" +
	"totalCoins\x18\x03 \x01(\x05R\n" +
	"totalCoinsB\x1dZ\x1bkratos-admin/pb/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_common_proto_rawDescOnce sync.Once
	file_admin_v1_common_proto_rawDescData []byte
)

func file_admin_v1_common_proto_rawDescGZIP() []byte {
	file_admin_v1_common_proto_rawDescOnce.Do(func() {
		file_admin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_common_proto_rawDesc), len(file_admin_v1_common_proto_rawDesc)))
	})
	return file_admin_v1_common_proto_rawDescData
}

var file_admin_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_v1_common_proto_goTypes = []any{
	(*PageOption)(nil),       // 0: admin.v1.PageOption
	(*PageInfo)(nil),         // 1: admin.v1.PageInfo
	(*EmptyReply)(nil),       // 2: admin.v1.EmptyReply
	(*SegmentGroupItem)(nil), // 3: admin.v1.SegmentGroupItem
	(*SegmentGroupInfo)(nil), // 4: admin.v1.SegmentGroupInfo
	(*UserBalance)(nil),      // 5: admin.v1.UserBalance
}
var file_admin_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_v1_common_proto_init() }
func file_admin_v1_common_proto_init() {
	if File_admin_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_common_proto_rawDesc), len(file_admin_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_common_proto_goTypes,
		DependencyIndexes: file_admin_v1_common_proto_depIdxs,
		MessageInfos:      file_admin_v1_common_proto_msgTypes,
	}.Build()
	File_admin_v1_common_proto = out.File
	file_admin_v1_common_proto_goTypes = nil
	file_admin_v1_common_proto_depIdxs = nil
}
