// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/common.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PageOption with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PageOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageOption with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PageOptionMultiError, or
// nil if none found.
func (m *PageOption) ValidateAll() error {
	return m.validate(true)
}

func (m *PageOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetIndex() < 0 {
		err := PageOptionValidationError{
			field:  "Index",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSize() < 0 {
		err := PageOptionValidationError{
			field:  "Size",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PageOptionMultiError(errors)
	}

	return nil
}

// PageOptionMultiError is an error wrapping multiple validation errors
// returned by PageOption.ValidateAll() if the designated constraints aren't met.
type PageOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageOptionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageOptionMultiError) AllErrors() []error { return m }

// PageOptionValidationError is the validation error returned by
// PageOption.Validate if the designated constraints aren't met.
type PageOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageOptionValidationError) ErrorName() string { return "PageOptionValidationError" }

// Error satisfies the builtin error interface
func (e PageOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageOptionValidationError{}

// Validate checks the field values on PageInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PageInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PageInfoMultiError, or nil
// if none found.
func (m *PageInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *PageInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Index

	// no validation rules for Size

	// no validation rules for Next

	// no validation rules for Total

	// no validation rules for IsEnd

	if len(errors) > 0 {
		return PageInfoMultiError(errors)
	}

	return nil
}

// PageInfoMultiError is an error wrapping multiple validation errors returned
// by PageInfo.ValidateAll() if the designated constraints aren't met.
type PageInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageInfoMultiError) AllErrors() []error { return m }

// PageInfoValidationError is the validation error returned by
// PageInfo.Validate if the designated constraints aren't met.
type PageInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageInfoValidationError) ErrorName() string { return "PageInfoValidationError" }

// Error satisfies the builtin error interface
func (e PageInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageInfoValidationError{}

// Validate checks the field values on EmptyReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EmptyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EmptyReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EmptyReplyMultiError, or
// nil if none found.
func (m *EmptyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *EmptyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EmptyReplyMultiError(errors)
	}

	return nil
}

// EmptyReplyMultiError is an error wrapping multiple validation errors
// returned by EmptyReply.ValidateAll() if the designated constraints aren't met.
type EmptyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmptyReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmptyReplyMultiError) AllErrors() []error { return m }

// EmptyReplyValidationError is the validation error returned by
// EmptyReply.Validate if the designated constraints aren't met.
type EmptyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmptyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmptyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmptyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmptyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmptyReplyValidationError) ErrorName() string { return "EmptyReplyValidationError" }

// Error satisfies the builtin error interface
func (e EmptyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmptyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmptyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmptyReplyValidationError{}

// Validate checks the field values on SegmentGroupItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SegmentGroupItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SegmentGroupItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SegmentGroupItemMultiError, or nil if none found.
func (m *SegmentGroupItem) ValidateAll() error {
	return m.validate(true)
}

func (m *SegmentGroupItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SegmentId

	// no validation rules for Weight

	// no validation rules for GroupId

	if len(errors) > 0 {
		return SegmentGroupItemMultiError(errors)
	}

	return nil
}

// SegmentGroupItemMultiError is an error wrapping multiple validation errors
// returned by SegmentGroupItem.ValidateAll() if the designated constraints
// aren't met.
type SegmentGroupItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SegmentGroupItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SegmentGroupItemMultiError) AllErrors() []error { return m }

// SegmentGroupItemValidationError is the validation error returned by
// SegmentGroupItem.Validate if the designated constraints aren't met.
type SegmentGroupItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SegmentGroupItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SegmentGroupItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SegmentGroupItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SegmentGroupItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SegmentGroupItemValidationError) ErrorName() string { return "SegmentGroupItemValidationError" }

// Error satisfies the builtin error interface
func (e SegmentGroupItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSegmentGroupItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SegmentGroupItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SegmentGroupItemValidationError{}

// Validate checks the field values on SegmentGroupInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SegmentGroupInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SegmentGroupInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SegmentGroupInfoMultiError, or nil if none found.
func (m *SegmentGroupInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SegmentGroupInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SegmentId

	// no validation rules for Weight

	// no validation rules for GroupId

	// no validation rules for Name

	// no validation rules for GroupName

	if len(errors) > 0 {
		return SegmentGroupInfoMultiError(errors)
	}

	return nil
}

// SegmentGroupInfoMultiError is an error wrapping multiple validation errors
// returned by SegmentGroupInfo.ValidateAll() if the designated constraints
// aren't met.
type SegmentGroupInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SegmentGroupInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SegmentGroupInfoMultiError) AllErrors() []error { return m }

// SegmentGroupInfoValidationError is the validation error returned by
// SegmentGroupInfo.Validate if the designated constraints aren't met.
type SegmentGroupInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SegmentGroupInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SegmentGroupInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SegmentGroupInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SegmentGroupInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SegmentGroupInfoValidationError) ErrorName() string { return "SegmentGroupInfoValidationError" }

// Error satisfies the builtin error interface
func (e SegmentGroupInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSegmentGroupInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SegmentGroupInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SegmentGroupInfoValidationError{}

// Validate checks the field values on UserBalance with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserBalance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserBalance with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserBalanceMultiError, or
// nil if none found.
func (m *UserBalance) ValidateAll() error {
	return m.validate(true)
}

func (m *UserBalance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Coin

	// no validation rules for Bonus

	// no validation rules for TotalCoins

	if len(errors) > 0 {
		return UserBalanceMultiError(errors)
	}

	return nil
}

// UserBalanceMultiError is an error wrapping multiple validation errors
// returned by UserBalance.ValidateAll() if the designated constraints aren't met.
type UserBalanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserBalanceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserBalanceMultiError) AllErrors() []error { return m }

// UserBalanceValidationError is the validation error returned by
// UserBalance.Validate if the designated constraints aren't met.
type UserBalanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserBalanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserBalanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserBalanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserBalanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserBalanceValidationError) ErrorName() string { return "UserBalanceValidationError" }

// Error satisfies the builtin error interface
func (e UserBalanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserBalance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserBalanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserBalanceValidationError{}
