// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: admin/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_SUCCESS      ErrorReason = 0
	ErrorReason_Unauthorized ErrorReason = 401
	ErrorReason_Forbidden    ErrorReason = 403
	// user start with 11
	ErrorReason_UserLoginFailed          ErrorReason = 110001
	ErrorReason_UserNotLogin             ErrorReason = 110002
	ErrorReason_UserNotFound             ErrorReason = 110003
	ErrorReason_UserSegmentInvalidParams ErrorReason = 110004 // 用户分群参数错误
	ErrorReason_UserParamsError          ErrorReason = 110005
	// product start with 13
	ErrorReason_ProductNotFound    ErrorReason = 130001 // 商品不存在
	ErrorReason_ProductParamsError ErrorReason = 130002 // 商品参数错误
	// message start with 14
	ErrorReason_MessageInvalidParams  ErrorReason = 140001 // 消息无效参数
	ErrorReason_MessageSubscribeError ErrorReason = 140002 // 消息订阅失败
	ErrorReason_MessageSending        ErrorReason = 140003 // 消息发送中
	// Advertising start with 15
	ErrorReason_AdvertisingParamsError ErrorReason = 150001 // 广告参数错误
	ErrorReason_AdvertisingInUsing     ErrorReason = 150002 // 广告正在使用中
	// payment start with 16
	ErrorReason_PaymentStrategyNotFound            ErrorReason = 160001 // 支付策略不存在
	ErrorReason_PaymentStrategyTypeModifyForbidden ErrorReason = 160002 // 不允许修改 type = -1 的策略
	ErrorReason_PaymentOptimizerNotFound           ErrorReason = 160003 // 优化师不存在或不是优化师
	ErrorReason_PaymentAdvertisingNotFound         ErrorReason = 160004 // 广告推广位不存在
	ErrorReason_PaymentSaveFailed                  ErrorReason = 160005 // 支付策略保存失败
	ErrorReason_PaymentAccountStatus               ErrorReason = 160006 // 支付账户状态异常
	ErrorReason_PaymentBonusInsufficient           ErrorReason = 160007 // 支付账户扣减赠币余额不足
	ErrorReason_PaymentStrategyInvalidParams       ErrorReason = 160008 // 支付策略参数错误
	// whitelist error start with 18
	ErrorReason_WhiteListInvalidValue ErrorReason = 180001 // IP 格式非法
	ErrorReason_WhiteListAddFailed    ErrorReason = 180002 // 添加白名单失败
	// operate error start with 19
	ErrorReason_OperateAppVersionInvalid ErrorReason = 190001 // app版本不合法
	// permission error start with 19
	ErrorReason_PermissionInvalidParams ErrorReason = 190002 // 参数错误（缺少 deviceId、banType 等）
	// task error start with 20
	ErrorReason_TaskNotFound             ErrorReason = 200001
	ErrorReason_TaskModifyForbidden      ErrorReason = 200002 // 不允许修改
	ErrorReason_TaskHistoryInvalidParams ErrorReason = 200011 // 任务历史查询参数错误（缺少 deviceId、userId 等）
	// popup start with 21
	ErrorReason_PopupParamsError ErrorReason = 210001 // 弹窗参数错误
	ErrorReason_PopupNotFound    ErrorReason = 210002 // 弹窗不存在
	ErrorReason_PopupSaveFailed  ErrorReason = 210003 // 弹窗保存失败
	// tag start with 22
	ErrorReason_TagDeleteForbidden ErrorReason = 220001 // 不允许删除
	// foryou start with 23
	ErrorReason_ForyouStrategyParamsError ErrorReason = 230001 // foryou策略参数错误
	// material video start with 24
	ErrorReason_MaterialVideoParamsError ErrorReason = 240001 // 素材视频擦拭错误
	// activity start with 25
	ErrorReason_ActivityParamsError ErrorReason = 250001
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:      "SUCCESS",
		401:    "Unauthorized",
		403:    "Forbidden",
		110001: "UserLoginFailed",
		110002: "UserNotLogin",
		110003: "UserNotFound",
		110004: "UserSegmentInvalidParams",
		110005: "UserParamsError",
		130001: "ProductNotFound",
		130002: "ProductParamsError",
		140001: "MessageInvalidParams",
		140002: "MessageSubscribeError",
		140003: "MessageSending",
		150001: "AdvertisingParamsError",
		150002: "AdvertisingInUsing",
		160001: "PaymentStrategyNotFound",
		160002: "PaymentStrategyTypeModifyForbidden",
		160003: "PaymentOptimizerNotFound",
		160004: "PaymentAdvertisingNotFound",
		160005: "PaymentSaveFailed",
		160006: "PaymentAccountStatus",
		160007: "PaymentBonusInsufficient",
		160008: "PaymentStrategyInvalidParams",
		180001: "WhiteListInvalidValue",
		180002: "WhiteListAddFailed",
		190001: "OperateAppVersionInvalid",
		190002: "PermissionInvalidParams",
		200001: "TaskNotFound",
		200002: "TaskModifyForbidden",
		200011: "TaskHistoryInvalidParams",
		210001: "PopupParamsError",
		210002: "PopupNotFound",
		210003: "PopupSaveFailed",
		220001: "TagDeleteForbidden",
		230001: "ForyouStrategyParamsError",
		240001: "MaterialVideoParamsError",
		250001: "ActivityParamsError",
	}
	ErrorReason_value = map[string]int32{
		"SUCCESS":                            0,
		"Unauthorized":                       401,
		"Forbidden":                          403,
		"UserLoginFailed":                    110001,
		"UserNotLogin":                       110002,
		"UserNotFound":                       110003,
		"UserSegmentInvalidParams":           110004,
		"UserParamsError":                    110005,
		"ProductNotFound":                    130001,
		"ProductParamsError":                 130002,
		"MessageInvalidParams":               140001,
		"MessageSubscribeError":              140002,
		"MessageSending":                     140003,
		"AdvertisingParamsError":             150001,
		"AdvertisingInUsing":                 150002,
		"PaymentStrategyNotFound":            160001,
		"PaymentStrategyTypeModifyForbidden": 160002,
		"PaymentOptimizerNotFound":           160003,
		"PaymentAdvertisingNotFound":         160004,
		"PaymentSaveFailed":                  160005,
		"PaymentAccountStatus":               160006,
		"PaymentBonusInsufficient":           160007,
		"PaymentStrategyInvalidParams":       160008,
		"WhiteListInvalidValue":              180001,
		"WhiteListAddFailed":                 180002,
		"OperateAppVersionInvalid":           190001,
		"PermissionInvalidParams":            190002,
		"TaskNotFound":                       200001,
		"TaskModifyForbidden":                200002,
		"TaskHistoryInvalidParams":           200011,
		"PopupParamsError":                   210001,
		"PopupNotFound":                      210002,
		"PopupSaveFailed":                    210003,
		"TagDeleteForbidden":                 220001,
		"ForyouStrategyParamsError":          230001,
		"MaterialVideoParamsError":           240001,
		"ActivityParamsError":                250001,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_admin_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_admin_v1_error_reason_proto protoreflect.FileDescriptor

const file_admin_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1badmin/v1/error_reason.proto\x12\badmin.v1\x1a\x13errors/errors.proto*\xcc\t\n" +
	"\vErrorReason\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x17\n" +
	"\fUnauthorized\x10\x91\x03\x1a\x04\xa8E\x91\x03\x12\x14\n" +
	"\tForbidden\x10\x93\x03\x1a\x04\xa8E\x93\x03\x12\x1b\n" +
	"\x0fUserLoginFailed\x10\xb1\xdb\x06\x1a\x04\xa8E\x91\x03\x12\x18\n" +
	"\fUserNotLogin\x10\xb2\xdb\x06\x1a\x04\xa8E\x91\x03\x12\x18\n" +
	"\fUserNotFound\x10\xb3\xdb\x06\x1a\x04\xa8E\x94\x03\x12$\n" +
	"\x18UserSegmentInvalidParams\x10\xb4\xdb\x06\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x0fUserParamsError\x10\xb5\xdb\x06\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x0fProductNotFound\x10\xd1\xf7\a\x1a\x04\xa8E\x94\x03\x12\x1e\n" +
	"\x12ProductParamsError\x10\xd2\xf7\a\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x14MessageInvalidParams\x10\xe1\xc5\b\x1a\x04\xa8E\x90\x03\x12!\n" +
	"\x15MessageSubscribeError\x10\xe2\xc5\b\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x0eMessageSending\x10\xe3\xc5\b\x1a\x04\xa8E\x90\x03\x12\"\n" +
	"\x16AdvertisingParamsError\x10\xf1\x93\t\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x12AdvertisingInUsing\x10\xf2\x93\t\x1a\x04\xa8E\x90\x03\x12#\n" +
	"\x17PaymentStrategyNotFound\x10\x81\xe2\t\x1a\x04\xa8E\x94\x03\x12.\n" +
	"\"PaymentStrategyTypeModifyForbidden\x10\x82\xe2\t\x1a\x04\xa8E\x90\x03\x12$\n" +
	"\x18PaymentOptimizerNotFound\x10\x83\xe2\t\x1a\x04\xa8E\x94\x03\x12&\n" +
	"\x1aPaymentAdvertisingNotFound\x10\x84\xe2\t\x1a\x04\xa8E\x94\x03\x12\x1d\n" +
	"\x11PaymentSaveFailed\x10\x85\xe2\t\x1a\x04\xa8E\xf4\x03\x12 \n" +
	"\x14PaymentAccountStatus\x10\x86\xe2\t\x1a\x04\xa8E\x90\x03\x12$\n" +
	"\x18PaymentBonusInsufficient\x10\x87\xe2\t\x1a\x04\xa8E\x90\x03\x12(\n" +
	"\x1cPaymentStrategyInvalidParams\x10\x88\xe2\t\x1a\x04\xa8E\x90\x03\x12!\n" +
	"\x15WhiteListInvalidValue\x10\xa1\xfe\n" +
	"\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x12WhiteListAddFailed\x10\xa2\xfe\n" +
	"\x1a\x04\xa8E\xf4\x03\x12$\n" +
	"\x18OperateAppVersionInvalid\x10\xb1\xcc\v\x1a\x04\xa8E\x90\x03\x12#\n" +
	"\x17PermissionInvalidParams\x10\xb2\xcc\v\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\fTaskNotFound\x10\xc1\x9a\f\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x13TaskModifyForbidden\x10\u009a\f\x1a\x04\xa8E\x90\x03\x12$\n" +
	"\x18TaskHistoryInvalidParams\x10˚\f\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x10PopupParamsError\x10\xd1\xe8\f\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\rPopupNotFound\x10\xd2\xe8\f\x1a\x04\xa8E\x94\x03\x12\x1b\n" +
	"\x0fPopupSaveFailed\x10\xd3\xe8\f\x1a\x04\xa8E\xf4\x03\x12\x1e\n" +
	"\x12TagDeleteForbidden\x10\xe1\xb6\r\x1a\x04\xa8E\x90\x03\x12%\n" +
	"\x19ForyouStrategyParamsError\x10\xf1\x84\x0e\x1a\x04\xa8E\x90\x03\x12$\n" +
	"\x18MaterialVideoParamsError\x10\x81\xd3\x0e\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x13ActivityParamsError\x10\x91\xa1\x0f\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x03B\x1dZ\x1bkratos-admin/pb/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_error_reason_proto_rawDescOnce sync.Once
	file_admin_v1_error_reason_proto_rawDescData []byte
)

func file_admin_v1_error_reason_proto_rawDescGZIP() []byte {
	file_admin_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_admin_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_error_reason_proto_rawDesc), len(file_admin_v1_error_reason_proto_rawDesc)))
	})
	return file_admin_v1_error_reason_proto_rawDescData
}

var file_admin_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: admin.v1.ErrorReason
}
var file_admin_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_v1_error_reason_proto_init() }
func file_admin_v1_error_reason_proto_init() {
	if File_admin_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_error_reason_proto_rawDesc), len(file_admin_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_admin_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_admin_v1_error_reason_proto_enumTypes,
	}.Build()
	File_admin_v1_error_reason_proto = out.File
	file_admin_v1_error_reason_proto_goTypes = nil
	file_admin_v1_error_reason_proto_depIdxs = nil
}
