// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsSuccess(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SUCCESS.String() && e.Code == 500
}

func ErrorSuccess(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SUCCESS.String(), fmt.Sprintf(format, args...))
}

func IsUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Unauthorized.String() && e.Code == 401
}

func ErrorUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_Unauthorized.String(), fmt.Sprintf(format, args...))
}

func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_Forbidden.String() && e.Code == 403
}

func ErrorForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_Forbidden.String(), fmt.Sprintf(format, args...))
}

// user start with 11
func IsUserLoginFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserLoginFailed.String() && e.Code == 401
}

// user start with 11
func ErrorUserLoginFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UserLoginFailed.String(), fmt.Sprintf(format, args...))
}

func IsUserNotLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserNotLogin.String() && e.Code == 401
}

func ErrorUserNotLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UserNotLogin.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserNotFound.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_UserNotFound.String(), fmt.Sprintf(format, args...))
}

// 用户分群参数错误
func IsUserSegmentInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserSegmentInvalidParams.String() && e.Code == 400
}

// 用户分群参数错误
func ErrorUserSegmentInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_UserSegmentInvalidParams.String(), fmt.Sprintf(format, args...))
}

func IsUserParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserParamsError.String() && e.Code == 400
}

func ErrorUserParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_UserParamsError.String(), fmt.Sprintf(format, args...))
}

// product start with 13
func IsProductNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ProductNotFound.String() && e.Code == 404
}

// product start with 13
func ErrorProductNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_ProductNotFound.String(), fmt.Sprintf(format, args...))
}

// 商品参数错误
func IsProductParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ProductParamsError.String() && e.Code == 400
}

// 商品参数错误
func ErrorProductParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ProductParamsError.String(), fmt.Sprintf(format, args...))
}

// message start with 14
func IsMessageInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MessageInvalidParams.String() && e.Code == 400
}

// message start with 14
func ErrorMessageInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MessageInvalidParams.String(), fmt.Sprintf(format, args...))
}

// 消息订阅失败
func IsMessageSubscribeError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MessageSubscribeError.String() && e.Code == 400
}

// 消息订阅失败
func ErrorMessageSubscribeError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MessageSubscribeError.String(), fmt.Sprintf(format, args...))
}

// 消息发送中
func IsMessageSending(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MessageSending.String() && e.Code == 400
}

// 消息发送中
func ErrorMessageSending(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MessageSending.String(), fmt.Sprintf(format, args...))
}

// Advertising start with 15
func IsAdvertisingParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdvertisingParamsError.String() && e.Code == 400
}

// Advertising start with 15
func ErrorAdvertisingParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_AdvertisingParamsError.String(), fmt.Sprintf(format, args...))
}

// 广告正在使用中
func IsAdvertisingInUsing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AdvertisingInUsing.String() && e.Code == 400
}

// 广告正在使用中
func ErrorAdvertisingInUsing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_AdvertisingInUsing.String(), fmt.Sprintf(format, args...))
}

// payment start with 16
func IsPaymentStrategyNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentStrategyNotFound.String() && e.Code == 404
}

// payment start with 16
func ErrorPaymentStrategyNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PaymentStrategyNotFound.String(), fmt.Sprintf(format, args...))
}

// 不允许修改 type = -1 的策略
func IsPaymentStrategyTypeModifyForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentStrategyTypeModifyForbidden.String() && e.Code == 400
}

// 不允许修改 type = -1 的策略
func ErrorPaymentStrategyTypeModifyForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PaymentStrategyTypeModifyForbidden.String(), fmt.Sprintf(format, args...))
}

// 优化师不存在或不是优化师
func IsPaymentOptimizerNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentOptimizerNotFound.String() && e.Code == 404
}

// 优化师不存在或不是优化师
func ErrorPaymentOptimizerNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PaymentOptimizerNotFound.String(), fmt.Sprintf(format, args...))
}

// 广告推广位不存在
func IsPaymentAdvertisingNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentAdvertisingNotFound.String() && e.Code == 404
}

// 广告推广位不存在
func ErrorPaymentAdvertisingNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PaymentAdvertisingNotFound.String(), fmt.Sprintf(format, args...))
}

// 支付策略保存失败
func IsPaymentSaveFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentSaveFailed.String() && e.Code == 500
}

// 支付策略保存失败
func ErrorPaymentSaveFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PaymentSaveFailed.String(), fmt.Sprintf(format, args...))
}

// 支付账户状态异常
func IsPaymentAccountStatus(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentAccountStatus.String() && e.Code == 400
}

// 支付账户状态异常
func ErrorPaymentAccountStatus(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PaymentAccountStatus.String(), fmt.Sprintf(format, args...))
}

// 支付账户扣减赠币余额不足
func IsPaymentBonusInsufficient(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentBonusInsufficient.String() && e.Code == 400
}

// 支付账户扣减赠币余额不足
func ErrorPaymentBonusInsufficient(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PaymentBonusInsufficient.String(), fmt.Sprintf(format, args...))
}

// 支付策略参数错误
func IsPaymentStrategyInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PaymentStrategyInvalidParams.String() && e.Code == 400
}

// 支付策略参数错误
func ErrorPaymentStrategyInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PaymentStrategyInvalidParams.String(), fmt.Sprintf(format, args...))
}

// whitelist error start with 18
func IsWhiteListInvalidValue(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WhiteListInvalidValue.String() && e.Code == 400
}

// whitelist error start with 18
func ErrorWhiteListInvalidValue(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_WhiteListInvalidValue.String(), fmt.Sprintf(format, args...))
}

// 添加白名单失败
func IsWhiteListAddFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_WhiteListAddFailed.String() && e.Code == 500
}

// 添加白名单失败
func ErrorWhiteListAddFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_WhiteListAddFailed.String(), fmt.Sprintf(format, args...))
}

// operate error start with 19
func IsOperateAppVersionInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OperateAppVersionInvalid.String() && e.Code == 400
}

// operate error start with 19
func ErrorOperateAppVersionInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_OperateAppVersionInvalid.String(), fmt.Sprintf(format, args...))
}

// permission error start with 19
func IsPermissionInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PermissionInvalidParams.String() && e.Code == 400
}

// permission error start with 19
func ErrorPermissionInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PermissionInvalidParams.String(), fmt.Sprintf(format, args...))
}

// task error start with 20
func IsTaskNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TaskNotFound.String() && e.Code == 404
}

// task error start with 20
func ErrorTaskNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_TaskNotFound.String(), fmt.Sprintf(format, args...))
}

// 不允许修改
func IsTaskModifyForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TaskModifyForbidden.String() && e.Code == 400
}

// 不允许修改
func ErrorTaskModifyForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TaskModifyForbidden.String(), fmt.Sprintf(format, args...))
}

// 任务历史查询参数错误（缺少 deviceId、userId 等）
func IsTaskHistoryInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TaskHistoryInvalidParams.String() && e.Code == 400
}

// 任务历史查询参数错误（缺少 deviceId、userId 等）
func ErrorTaskHistoryInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TaskHistoryInvalidParams.String(), fmt.Sprintf(format, args...))
}

// popup start with 21
func IsPopupParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PopupParamsError.String() && e.Code == 400
}

// popup start with 21
func ErrorPopupParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_PopupParamsError.String(), fmt.Sprintf(format, args...))
}

// 弹窗不存在
func IsPopupNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PopupNotFound.String() && e.Code == 404
}

// 弹窗不存在
func ErrorPopupNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PopupNotFound.String(), fmt.Sprintf(format, args...))
}

// 弹窗保存失败
func IsPopupSaveFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PopupSaveFailed.String() && e.Code == 500
}

// 弹窗保存失败
func ErrorPopupSaveFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PopupSaveFailed.String(), fmt.Sprintf(format, args...))
}

// tag start with 22
func IsTagDeleteForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TagDeleteForbidden.String() && e.Code == 400
}

// tag start with 22
func ErrorTagDeleteForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_TagDeleteForbidden.String(), fmt.Sprintf(format, args...))
}

// foryou start with 23
func IsForyouStrategyParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ForyouStrategyParamsError.String() && e.Code == 400
}

// foryou start with 23
func ErrorForyouStrategyParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ForyouStrategyParamsError.String(), fmt.Sprintf(format, args...))
}

// material video start with 24
func IsMaterialVideoParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MaterialVideoParamsError.String() && e.Code == 400
}

// material video start with 24
func ErrorMaterialVideoParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_MaterialVideoParamsError.String(), fmt.Sprintf(format, args...))
}

// activity start with 25
func IsActivityParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ActivityParamsError.String() && e.Code == 400
}

// activity start with 25
func ErrorActivityParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ActivityParamsError.String(), fmt.Sprintf(format, args...))
}
