// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: admin/v1/permission.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 团队信息
type GroupInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 团队名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 数据隔离: 1 不隔离, 2 隔离
	DataIsolation int32 `protobuf:"varint,3,opt,name=dataIsolation,proto3" json:"dataIsolation,omitempty"`
	// 用户数量
	UserCount int32 `protobuf:"varint,4,opt,name=userCount,proto3" json:"userCount,omitempty"`
	// 团队创建时间
	CreateTime int64 `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 关联角色列表
	Roles []*GroupInfo_Role `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	// 操作人
	Operator      string `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_admin_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *GroupInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetDataIsolation() int32 {
	if x != nil {
		return x.DataIsolation
	}
	return 0
}

func (x *GroupInfo) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *GroupInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupInfo) GetRoles() []*GroupInfo_Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GroupInfo) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// 获取团队列表请求
type ListGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引
	PageIndex int32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 团队名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// ids
	Ids           []int64 `protobuf:"varint,4,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupRequest) Reset() {
	*x = ListGroupRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupRequest) ProtoMessage() {}

func (x *ListGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupRequest.ProtoReflect.Descriptor instead.
func (*ListGroupRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *ListGroupRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListGroupRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListGroupRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 获取团队列表回复
type ListGroupReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队列表
	List []*GroupInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页信息
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupReply) Reset() {
	*x = ListGroupReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupReply) ProtoMessage() {}

func (x *ListGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupReply.ProtoReflect.Descriptor instead.
func (*ListGroupReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *ListGroupReply) GetList() []*GroupInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListGroupReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 保存团队信息请求
type SaveGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 团队名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 数据隔离: 1 不隔离, 2 隔离
	DataIsolation int32 `protobuf:"varint,3,opt,name=dataIsolation,proto3" json:"dataIsolation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGroupRequest) Reset() {
	*x = SaveGroupRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGroupRequest) ProtoMessage() {}

func (x *SaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGroupRequest.ProtoReflect.Descriptor instead.
func (*SaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *SaveGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveGroupRequest) GetDataIsolation() int32 {
	if x != nil {
		return x.DataIsolation
	}
	return 0
}

// 保存团队信息回复
type SaveGroupReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGroupReply) Reset() {
	*x = SaveGroupReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGroupReply) ProtoMessage() {}

func (x *SaveGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGroupReply.ProtoReflect.Descriptor instead.
func (*SaveGroupReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{4}
}

func (x *SaveGroupReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除团队请求
type DeleteGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取团队成员列表请求
type ListGroupMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引
	PageIndex int32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// groupId
	GroupId int64 `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 模糊查询
	FuzzyQuery    string `protobuf:"bytes,4,opt,name=fuzzyQuery,proto3" json:"fuzzyQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMemberRequest) Reset() {
	*x = ListGroupMemberRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMemberRequest) ProtoMessage() {}

func (x *ListGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *ListGroupMemberRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListGroupMemberRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListGroupMemberRequest) GetFuzzyQuery() string {
	if x != nil {
		return x.FuzzyQuery
	}
	return ""
}

// 获取团队成员列表回复
type ListGroupMemberReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队成员列表
	List []*GroupMemberInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页信息
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMemberReply) Reset() {
	*x = ListGroupMemberReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMemberReply) ProtoMessage() {}

func (x *ListGroupMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMemberReply.ProtoReflect.Descriptor instead.
func (*ListGroupMemberReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *ListGroupMemberReply) GetList() []*GroupMemberInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListGroupMemberReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 团队成员信息
type GroupMemberInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 用户手机号
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 状态: 1 正常, 2 禁用
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// 角色列表
	Roles []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	// 数据权限级别: 1 仅查看个人数据, 2 可查看团队数据
	PrivilegeLevel int32 `protobuf:"varint,6,opt,name=privilegeLevel,proto3" json:"privilegeLevel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupMemberInfo) Reset() {
	*x = GroupMemberInfo{}
	mi := &file_admin_v1_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberInfo) ProtoMessage() {}

func (x *GroupMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberInfo.ProtoReflect.Descriptor instead.
func (*GroupMemberInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMemberInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMemberInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMemberInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GroupMemberInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupMemberInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GroupMemberInfo) GetPrivilegeLevel() int32 {
	if x != nil {
		return x.PrivilegeLevel
	}
	return 0
}

// 保存团队成员信息请求
type SaveGroupMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队id
	GroupId int64 `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// 用户id
	UserId int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 数据权限级别: 1 仅查看个人数据, 2 可查看团队数据
	PrivilegeLevel int32 `protobuf:"varint,3,opt,name=privilegeLevel,proto3" json:"privilegeLevel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveGroupMemberRequest) Reset() {
	*x = SaveGroupMemberRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGroupMemberRequest) ProtoMessage() {}

func (x *SaveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*SaveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{9}
}

func (x *SaveGroupMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SaveGroupMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveGroupMemberRequest) GetPrivilegeLevel() int32 {
	if x != nil {
		return x.PrivilegeLevel
	}
	return 0
}

// 角色信息
type RoleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 用户数量
	UserCount int32 `protobuf:"varint,3,opt,name=userCount,proto3" json:"userCount,omitempty"`
	// 创建人
	Operator string `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	// 角色创建时间
	CreateTime int64 `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 角色团队
	Group         *RoleInfo_RoleGroup `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_admin_v1_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{10}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *RoleInfo) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *RoleInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RoleInfo) GetGroup() *RoleInfo_RoleGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// 获取角色列表请求
type ListRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引
	PageIndex int32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 角色名称
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{11}
}

func (x *ListRoleRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListRoleRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 获取角色列表回复
type ListRoleReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色列表
	List []*RoleInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页信息
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleReply) Reset() {
	*x = ListRoleReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReply) ProtoMessage() {}

func (x *ListRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReply.ProtoReflect.Descriptor instead.
func (*ListRoleReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{12}
}

func (x *ListRoleReply) GetList() []*RoleInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRoleReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 保存角色
type SaveRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 团队id
	GroupId       int64 `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRoleRequest) Reset() {
	*x = SaveRoleRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoleRequest) ProtoMessage() {}

func (x *SaveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoleRequest.ProtoReflect.Descriptor instead.
func (*SaveRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{13}
}

func (x *SaveRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveRoleRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 保存角色回复
type SaveRoleReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRoleReply) Reset() {
	*x = SaveRoleReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoleReply) ProtoMessage() {}

func (x *SaveRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoleReply.ProtoReflect.Descriptor instead.
func (*SaveRoleReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{14}
}

func (x *SaveRoleReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除角色
type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 角色成员
type RoleMemberInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 用户手机号
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	// 状态: 1 正常, 2 禁用
	Status        int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleMemberInfo) Reset() {
	*x = RoleMemberInfo{}
	mi := &file_admin_v1_permission_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleMemberInfo) ProtoMessage() {}

func (x *RoleMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleMemberInfo.ProtoReflect.Descriptor instead.
func (*RoleMemberInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{16}
}

func (x *RoleMemberInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoleMemberInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleMemberInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RoleMemberInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 角色成员列表请求
type ListRoleMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页索引
	PageIndex int32 `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	// 分页大小
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// roleId
	RoleId int64 `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	// 模糊查询
	FuzzyQuery    string `protobuf:"bytes,4,opt,name=fuzzyQuery,proto3" json:"fuzzyQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleMemberRequest) Reset() {
	*x = ListRoleMemberRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleMemberRequest) ProtoMessage() {}

func (x *ListRoleMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleMemberRequest.ProtoReflect.Descriptor instead.
func (*ListRoleMemberRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{17}
}

func (x *ListRoleMemberRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListRoleMemberRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleMemberRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ListRoleMemberRequest) GetFuzzyQuery() string {
	if x != nil {
		return x.FuzzyQuery
	}
	return ""
}

// 角色成员列表回复
type ListRoleMemberReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色成员列表
	List []*RoleMemberInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页信息
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleMemberReply) Reset() {
	*x = ListRoleMemberReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleMemberReply) ProtoMessage() {}

func (x *ListRoleMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleMemberReply.ProtoReflect.Descriptor instead.
func (*ListRoleMemberReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{18}
}

func (x *ListRoleMemberReply) GetList() []*RoleMemberInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRoleMemberReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// 保存角色权限
type SaveRolePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	RoleId int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	// 资源id
	ResourceIds   []int64 `protobuf:"varint,2,rep,packed,name=resourceIds,proto3" json:"resourceIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRolePermissionRequest) Reset() {
	*x = SaveRolePermissionRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRolePermissionRequest) ProtoMessage() {}

func (x *SaveRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*SaveRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{19}
}

func (x *SaveRolePermissionRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *SaveRolePermissionRequest) GetResourceIds() []int64 {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

// 获取角色权限
type ListRolePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	RoleId        int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionRequest) Reset() {
	*x = ListRolePermissionRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionRequest) ProtoMessage() {}

func (x *ListRolePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionRequest.ProtoReflect.Descriptor instead.
func (*ListRolePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{20}
}

func (x *ListRolePermissionRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 获取角色权限回复
type ListRolePermissionReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限列表
	List          []*RoleResource `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePermissionReply) Reset() {
	*x = ListRolePermissionReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePermissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePermissionReply) ProtoMessage() {}

func (x *ListRolePermissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePermissionReply.ProtoReflect.Descriptor instead.
func (*ListRolePermissionReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{21}
}

func (x *ListRolePermissionReply) GetList() []*RoleResource {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 资源名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 资源类型: menu, page, button, api
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// 是否拥有权限
	HasPermission bool `protobuf:"varint,4,opt,name=hasPermission,proto3" json:"hasPermission,omitempty"`
	// 子资源
	Children      []*RoleResource `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResource) Reset() {
	*x = RoleResource{}
	mi := &file_admin_v1_permission_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResource) ProtoMessage() {}

func (x *RoleResource) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResource.ProtoReflect.Descriptor instead.
func (*RoleResource) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{22}
}

func (x *RoleResource) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoleResource) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

func (x *RoleResource) GetChildren() []*RoleResource {
	if x != nil {
		return x.Children
	}
	return nil
}

// 资源信息
type ResourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 资源父id
	ParentId int64 `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	// 资源名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 资源类型: menu, page, button, api
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// 资源路径
	Path string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// 权重
	Weight int32 `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// 关联api
	Apis []string `protobuf:"bytes,7,rep,name=apis,proto3" json:"apis,omitempty"`
	// 子资源
	Children      []*ResourceInfo `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_admin_v1_permission_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{23}
}

func (x *ResourceInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResourceInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ResourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResourceInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ResourceInfo) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

func (x *ResourceInfo) GetChildren() []*ResourceInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

// 获取菜单列表
type ListResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceRequest) Reset() {
	*x = ListResourceRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceRequest) ProtoMessage() {}

func (x *ListResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceRequest.ProtoReflect.Descriptor instead.
func (*ListResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{24}
}

// 获取菜单列表回复
type ListResourceReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 菜单列表
	List          []*ResourceInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceReply) Reset() {
	*x = ListResourceReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceReply) ProtoMessage() {}

func (x *ListResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceReply.ProtoReflect.Descriptor instead.
func (*ListResourceReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{25}
}

func (x *ListResourceReply) GetList() []*ResourceInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 保存资源
type SaveResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 资源父id
	ParentId int64 `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	// 资源名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 资源类型: menu, page, button, api
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// 资源路径
	Path string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// 权重
	Weight int32 `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// 关联api
	Apis          []string `protobuf:"bytes,7,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResourceRequest) Reset() {
	*x = SaveResourceRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResourceRequest) ProtoMessage() {}

func (x *SaveResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResourceRequest.ProtoReflect.Descriptor instead.
func (*SaveResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{26}
}

func (x *SaveResourceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveResourceRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *SaveResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveResourceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SaveResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SaveResourceRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SaveResourceRequest) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

// 保存资源回复
type SaveResourceReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResourceReply) Reset() {
	*x = SaveResourceReply{}
	mi := &file_admin_v1_permission_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResourceReply) ProtoMessage() {}

func (x *SaveResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResourceReply.ProtoReflect.Descriptor instead.
func (*SaveResourceReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{27}
}

func (x *SaveResourceReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除资源
type DeleteResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteResourceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 导入资源
type ImportResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源列表
	Data          []*ResourceInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResourceRequest) Reset() {
	*x = ImportResourceRequest{}
	mi := &file_admin_v1_permission_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResourceRequest) ProtoMessage() {}

func (x *ImportResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResourceRequest.ProtoReflect.Descriptor instead.
func (*ImportResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{29}
}

func (x *ImportResourceRequest) GetData() []*ResourceInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupInfo_Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 角色名称
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo_Role) Reset() {
	*x = GroupInfo_Role{}
	mi := &file_admin_v1_permission_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo_Role) ProtoMessage() {}

func (x *GroupInfo_Role) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo_Role.ProtoReflect.Descriptor instead.
func (*GroupInfo_Role) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GroupInfo_Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInfo_Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleInfo_RoleGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 团队id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 团队名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 数据隔离: 1 不隔离, 2 隔离
	DataIsolation int32 `protobuf:"varint,3,opt,name=dataIsolation,proto3" json:"dataIsolation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo_RoleGroup) Reset() {
	*x = RoleInfo_RoleGroup{}
	mi := &file_admin_v1_permission_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo_RoleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo_RoleGroup) ProtoMessage() {}

func (x *RoleInfo_RoleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_permission_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo_RoleGroup.ProtoReflect.Descriptor instead.
func (*RoleInfo_RoleGroup) Descriptor() ([]byte, []int) {
	return file_admin_v1_permission_proto_rawDescGZIP(), []int{10, 0}
}

func (x *RoleInfo_RoleGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo_RoleGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo_RoleGroup) GetDataIsolation() int32 {
	if x != nil {
		return x.DataIsolation
	}
	return 0
}

var File_admin_v1_permission_proto protoreflect.FileDescriptor

const file_admin_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x19admin/v1/permission.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x15admin/v1/common.proto\"\x8b\x02\n" +
	"\tGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\rdataIsolation\x18\x03 \x01(\x05R\rdataIsolation\x12\x1c\n" +
	"\tuserCount\x18\x04 \x01(\x05R\tuserCount\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03R\n" +
	"createTime\x12.\n" +
	"\x05roles\x18\x06 \x03(\v2\x18.admin.v1.GroupInfo.RoleR\x05roles\x12\x1a\n" +
	"\boperator\x18\a \x01(\tR\boperator\x1a*\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"r\n" +
	"\x10ListGroupRequest\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\x03R\x03ids\"a\n" +
	"\x0eListGroupReply\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.admin.v1.GroupInfoR\x04list\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.admin.v1.PageInfoR\x04page\"p\n" +
	"\x10SaveGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12/\n" +
	"\rdataIsolation\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x040\x010\x02R\rdataIsolation\" \n" +
	"\x0eSaveGroupReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12DeleteGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x95\x01\n" +
	"\x16ListGroupMemberRequest\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\agroupId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\agroupId\x12\x1e\n" +
	"\n" +
	"fuzzyQuery\x18\x04 \x01(\tR\n" +
	"fuzzyQuery\"m\n" +
	"\x14ListGroupMemberReply\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.admin.v1.GroupMemberInfoR\x04list\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.admin.v1.PageInfoR\x04page\"\xb1\x01\n" +
	"\x0fGroupMemberInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12&\n" +
	"\x0eprivilegeLevel\x18\x06 \x01(\x05R\x0eprivilegeLevel\"r\n" +
	"\x16SaveGroupMemberRequest\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0eprivilegeLevel\x18\x03 \x01(\x05R\x0eprivilegeLevel\"\x93\x02\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tuserCount\x18\x03 \x01(\x05R\tuserCount\x12\x1a\n" +
	"\boperator\x18\x04 \x01(\tR\boperator\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\x03R\n" +
	"createTime\x122\n" +
	"\x05group\x18\x06 \x01(\v2\x1c.admin.v1.RoleInfo.RoleGroupR\x05group\x1aU\n" +
	"\tRoleGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\rdataIsolation\x18\x03 \x01(\x05R\rdataIsolation\"_\n" +
	"\x0fListRoleRequest\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"_\n" +
	"\rListRoleReply\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.admin.v1.RoleInfoR\x04list\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.admin.v1.PageInfoR\x04page\"a\n" +
	"\x0fSaveRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12!\n" +
	"\agroupId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\agroupId\"\x1f\n" +
	"\rSaveRoleReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"r\n" +
	"\x0eRoleMemberInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x92\x01\n" +
	"\x15ListRoleMemberRequest\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\x06roleId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06roleId\x12\x1e\n" +
	"\n" +
	"fuzzyQuery\x18\x04 \x01(\tR\n" +
	"fuzzyQuery\"k\n" +
	"\x13ListRoleMemberReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.admin.v1.RoleMemberInfoR\x04list\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.admin.v1.PageInfoR\x04page\"U\n" +
	"\x19SaveRolePermissionRequest\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\x12 \n" +
	"\vresourceIds\x18\x02 \x03(\x03R\vresourceIds\"3\n" +
	"\x19ListRolePermissionRequest\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\"E\n" +
	"\x17ListRolePermissionReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.admin.v1.RoleResourceR\x04list\"\xa0\x01\n" +
	"\fRoleResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12$\n" +
	"\rhasPermission\x18\x04 \x01(\bR\rhasPermission\x122\n" +
	"\bchildren\x18\x05 \x03(\v2\x16.admin.v1.RoleResourceR\bchildren\"\xd6\x01\n" +
	"\fResourceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04apis\x18\a \x03(\tR\x04apis\x122\n" +
	"\bchildren\x18\b \x03(\v2\x16.admin.v1.ResourceInfoR\bchildren\"\x15\n" +
	"\x13ListResourceRequest\"?\n" +
	"\x11ListResourceReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.admin.v1.ResourceInfoR\x04list\"\xdb\x01\n" +
	"\x13SaveResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x122\n" +
	"\x04type\x18\x04 \x01(\tB\x1e\xfaB\x1br\x19R\x04menuR\x04pageR\x06buttonR\x03apiR\x04type\x12\x1b\n" +
	"\x04path\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04path\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04apis\x18\a \x03(\tR\x04apis\"#\n" +
	"\x11SaveResourceReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"'\n" +
	"\x15DeleteResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x15ImportResourceRequest\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.admin.v1.ResourceInfoR\x04data2\xba\r\n" +
	"\n" +
	"Permission\x12d\n" +
	"\tListGroup\x12\x1a.admin.v1.ListGroupRequest\x1a\x18.admin.v1.ListGroupReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/permission/group/list\x12g\n" +
	"\tSaveGroup\x12\x1a.admin.v1.SaveGroupRequest\x1a\x18.admin.v1.SaveGroupReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/permission/group/save\x12f\n" +
	"\vDeleteGroup\x12\x1c.admin.v1.DeleteGroupRequest\x1a\x14.admin.v1.EmptyReply\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/permission/group/delete\x12}\n" +
	"\x0fListGroupMember\x12 .admin.v1.ListGroupMemberRequest\x1a\x1e.admin.v1.ListGroupMemberReply\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/permission/group/member/list\x12v\n" +
	"\x0fSaveGroupMember\x12 .admin.v1.SaveGroupMemberRequest\x1a\x14.admin.v1.EmptyReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/permission/group/member/save\x12`\n" +
	"\bListRole\x12\x19.admin.v1.ListRoleRequest\x1a\x17.admin.v1.ListRoleReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/permission/role/list\x12c\n" +
	"\bSaveRole\x12\x19.admin.v1.SaveRoleRequest\x1a\x17.admin.v1.SaveRoleReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/permission/role/save\x12c\n" +
	"\n" +
	"DeleteRole\x12\x1b.admin.v1.DeleteRoleRequest\x1a\x14.admin.v1.EmptyReply\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/permission/role/delete\x12\x89\x01\n" +
	"\x12ListRolePermission\x12#.admin.v1.ListRolePermissionRequest\x1a!.admin.v1.ListRolePermissionReply\"+\x82\xd3\xe4\x93\x02%\x12#/v1/permission/role/permission/list\x12\x7f\n" +
	"\x12SaveRolePermission\x12#.admin.v1.SaveRolePermissionRequest\x1a\x14.admin.v1.EmptyReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/permission/role/permission/save\x12y\n" +
	"\x0eListRoleMember\x12\x1f.admin.v1.ListRoleMemberRequest\x1a\x1d.admin.v1.ListRoleMemberReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/permission/role/member/list\x12p\n" +
	"\fListResource\x12\x1d.admin.v1.ListResourceRequest\x1a\x1b.admin.v1.ListResourceReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/permission/resource/list\x12s\n" +
	"\fSaveResource\x12\x1d.admin.v1.SaveResourceRequest\x1a\x1b.admin.v1.SaveResourceReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/permission/resource/save\x12o\n" +
	"\x0eDeleteResource\x12\x1f.admin.v1.DeleteResourceRequest\x1a\x14.admin.v1.EmptyReply\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/permission/resource/delete\x12r\n" +
	"\x0eImportResource\x12\x1f.admin.v1.ImportResourceRequest\x1a\x14.admin.v1.EmptyReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/permission/resource/importB\x1dZ\x1bkratos-admin/pb/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_permission_proto_rawDescOnce sync.Once
	file_admin_v1_permission_proto_rawDescData []byte
)

func file_admin_v1_permission_proto_rawDescGZIP() []byte {
	file_admin_v1_permission_proto_rawDescOnce.Do(func() {
		file_admin_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_permission_proto_rawDesc), len(file_admin_v1_permission_proto_rawDesc)))
	})
	return file_admin_v1_permission_proto_rawDescData
}

var file_admin_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_admin_v1_permission_proto_goTypes = []any{
	(*GroupInfo)(nil),                 // 0: admin.v1.GroupInfo
	(*ListGroupRequest)(nil),          // 1: admin.v1.ListGroupRequest
	(*ListGroupReply)(nil),            // 2: admin.v1.ListGroupReply
	(*SaveGroupRequest)(nil),          // 3: admin.v1.SaveGroupRequest
	(*SaveGroupReply)(nil),            // 4: admin.v1.SaveGroupReply
	(*DeleteGroupRequest)(nil),        // 5: admin.v1.DeleteGroupRequest
	(*ListGroupMemberRequest)(nil),    // 6: admin.v1.ListGroupMemberRequest
	(*ListGroupMemberReply)(nil),      // 7: admin.v1.ListGroupMemberReply
	(*GroupMemberInfo)(nil),           // 8: admin.v1.GroupMemberInfo
	(*SaveGroupMemberRequest)(nil),    // 9: admin.v1.SaveGroupMemberRequest
	(*RoleInfo)(nil),                  // 10: admin.v1.RoleInfo
	(*ListRoleRequest)(nil),           // 11: admin.v1.ListRoleRequest
	(*ListRoleReply)(nil),             // 12: admin.v1.ListRoleReply
	(*SaveRoleRequest)(nil),           // 13: admin.v1.SaveRoleRequest
	(*SaveRoleReply)(nil),             // 14: admin.v1.SaveRoleReply
	(*DeleteRoleRequest)(nil),         // 15: admin.v1.DeleteRoleRequest
	(*RoleMemberInfo)(nil),            // 16: admin.v1.RoleMemberInfo
	(*ListRoleMemberRequest)(nil),     // 17: admin.v1.ListRoleMemberRequest
	(*ListRoleMemberReply)(nil),       // 18: admin.v1.ListRoleMemberReply
	(*SaveRolePermissionRequest)(nil), // 19: admin.v1.SaveRolePermissionRequest
	(*ListRolePermissionRequest)(nil), // 20: admin.v1.ListRolePermissionRequest
	(*ListRolePermissionReply)(nil),   // 21: admin.v1.ListRolePermissionReply
	(*RoleResource)(nil),              // 22: admin.v1.RoleResource
	(*ResourceInfo)(nil),              // 23: admin.v1.ResourceInfo
	(*ListResourceRequest)(nil),       // 24: admin.v1.ListResourceRequest
	(*ListResourceReply)(nil),         // 25: admin.v1.ListResourceReply
	(*SaveResourceRequest)(nil),       // 26: admin.v1.SaveResourceRequest
	(*SaveResourceReply)(nil),         // 27: admin.v1.SaveResourceReply
	(*DeleteResourceRequest)(nil),     // 28: admin.v1.DeleteResourceRequest
	(*ImportResourceRequest)(nil),     // 29: admin.v1.ImportResourceRequest
	(*GroupInfo_Role)(nil),            // 30: admin.v1.GroupInfo.Role
	(*RoleInfo_RoleGroup)(nil),        // 31: admin.v1.RoleInfo.RoleGroup
	(*PageInfo)(nil),                  // 32: admin.v1.PageInfo
	(*EmptyReply)(nil),                // 33: admin.v1.EmptyReply
}
var file_admin_v1_permission_proto_depIdxs = []int32{
	30, // 0: admin.v1.GroupInfo.roles:type_name -> admin.v1.GroupInfo.Role
	0,  // 1: admin.v1.ListGroupReply.list:type_name -> admin.v1.GroupInfo
	32, // 2: admin.v1.ListGroupReply.page:type_name -> admin.v1.PageInfo
	8,  // 3: admin.v1.ListGroupMemberReply.list:type_name -> admin.v1.GroupMemberInfo
	32, // 4: admin.v1.ListGroupMemberReply.page:type_name -> admin.v1.PageInfo
	31, // 5: admin.v1.RoleInfo.group:type_name -> admin.v1.RoleInfo.RoleGroup
	10, // 6: admin.v1.ListRoleReply.list:type_name -> admin.v1.RoleInfo
	32, // 7: admin.v1.ListRoleReply.page:type_name -> admin.v1.PageInfo
	16, // 8: admin.v1.ListRoleMemberReply.list:type_name -> admin.v1.RoleMemberInfo
	32, // 9: admin.v1.ListRoleMemberReply.page:type_name -> admin.v1.PageInfo
	22, // 10: admin.v1.ListRolePermissionReply.list:type_name -> admin.v1.RoleResource
	22, // 11: admin.v1.RoleResource.children:type_name -> admin.v1.RoleResource
	23, // 12: admin.v1.ResourceInfo.children:type_name -> admin.v1.ResourceInfo
	23, // 13: admin.v1.ListResourceReply.list:type_name -> admin.v1.ResourceInfo
	23, // 14: admin.v1.ImportResourceRequest.data:type_name -> admin.v1.ResourceInfo
	1,  // 15: admin.v1.Permission.ListGroup:input_type -> admin.v1.ListGroupRequest
	3,  // 16: admin.v1.Permission.SaveGroup:input_type -> admin.v1.SaveGroupRequest
	5,  // 17: admin.v1.Permission.DeleteGroup:input_type -> admin.v1.DeleteGroupRequest
	6,  // 18: admin.v1.Permission.ListGroupMember:input_type -> admin.v1.ListGroupMemberRequest
	9,  // 19: admin.v1.Permission.SaveGroupMember:input_type -> admin.v1.SaveGroupMemberRequest
	11, // 20: admin.v1.Permission.ListRole:input_type -> admin.v1.ListRoleRequest
	13, // 21: admin.v1.Permission.SaveRole:input_type -> admin.v1.SaveRoleRequest
	15, // 22: admin.v1.Permission.DeleteRole:input_type -> admin.v1.DeleteRoleRequest
	20, // 23: admin.v1.Permission.ListRolePermission:input_type -> admin.v1.ListRolePermissionRequest
	19, // 24: admin.v1.Permission.SaveRolePermission:input_type -> admin.v1.SaveRolePermissionRequest
	17, // 25: admin.v1.Permission.ListRoleMember:input_type -> admin.v1.ListRoleMemberRequest
	24, // 26: admin.v1.Permission.ListResource:input_type -> admin.v1.ListResourceRequest
	26, // 27: admin.v1.Permission.SaveResource:input_type -> admin.v1.SaveResourceRequest
	28, // 28: admin.v1.Permission.DeleteResource:input_type -> admin.v1.DeleteResourceRequest
	29, // 29: admin.v1.Permission.ImportResource:input_type -> admin.v1.ImportResourceRequest
	2,  // 30: admin.v1.Permission.ListGroup:output_type -> admin.v1.ListGroupReply
	4,  // 31: admin.v1.Permission.SaveGroup:output_type -> admin.v1.SaveGroupReply
	33, // 32: admin.v1.Permission.DeleteGroup:output_type -> admin.v1.EmptyReply
	7,  // 33: admin.v1.Permission.ListGroupMember:output_type -> admin.v1.ListGroupMemberReply
	33, // 34: admin.v1.Permission.SaveGroupMember:output_type -> admin.v1.EmptyReply
	12, // 35: admin.v1.Permission.ListRole:output_type -> admin.v1.ListRoleReply
	14, // 36: admin.v1.Permission.SaveRole:output_type -> admin.v1.SaveRoleReply
	33, // 37: admin.v1.Permission.DeleteRole:output_type -> admin.v1.EmptyReply
	21, // 38: admin.v1.Permission.ListRolePermission:output_type -> admin.v1.ListRolePermissionReply
	33, // 39: admin.v1.Permission.SaveRolePermission:output_type -> admin.v1.EmptyReply
	18, // 40: admin.v1.Permission.ListRoleMember:output_type -> admin.v1.ListRoleMemberReply
	25, // 41: admin.v1.Permission.ListResource:output_type -> admin.v1.ListResourceReply
	27, // 42: admin.v1.Permission.SaveResource:output_type -> admin.v1.SaveResourceReply
	33, // 43: admin.v1.Permission.DeleteResource:output_type -> admin.v1.EmptyReply
	33, // 44: admin.v1.Permission.ImportResource:output_type -> admin.v1.EmptyReply
	30, // [30:45] is the sub-list for method output_type
	15, // [15:30] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_admin_v1_permission_proto_init() }
func file_admin_v1_permission_proto_init() {
	if File_admin_v1_permission_proto != nil {
		return
	}
	file_admin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_permission_proto_rawDesc), len(file_admin_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_permission_proto_goTypes,
		DependencyIndexes: file_admin_v1_permission_proto_depIdxs,
		MessageInfos:      file_admin_v1_permission_proto_msgTypes,
	}.Build()
	File_admin_v1_permission_proto = out.File
	file_admin_v1_permission_proto_goTypes = nil
	file_admin_v1_permission_proto_depIdxs = nil
}
