// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: admin/v1/permission.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPermissionDeleteGroup = "/admin.v1.Permission/DeleteGroup"
const OperationPermissionDeleteResource = "/admin.v1.Permission/DeleteResource"
const OperationPermissionDeleteRole = "/admin.v1.Permission/DeleteRole"
const OperationPermissionImportResource = "/admin.v1.Permission/ImportResource"
const OperationPermissionListGroup = "/admin.v1.Permission/ListGroup"
const OperationPermissionListGroupMember = "/admin.v1.Permission/ListGroupMember"
const OperationPermissionListResource = "/admin.v1.Permission/ListResource"
const OperationPermissionListRole = "/admin.v1.Permission/ListRole"
const OperationPermissionListRoleMember = "/admin.v1.Permission/ListRoleMember"
const OperationPermissionListRolePermission = "/admin.v1.Permission/ListRolePermission"
const OperationPermissionSaveGroup = "/admin.v1.Permission/SaveGroup"
const OperationPermissionSaveGroupMember = "/admin.v1.Permission/SaveGroupMember"
const OperationPermissionSaveResource = "/admin.v1.Permission/SaveResource"
const OperationPermissionSaveRole = "/admin.v1.Permission/SaveRole"
const OperationPermissionSaveRolePermission = "/admin.v1.Permission/SaveRolePermission"

type PermissionHTTPServer interface {
	// DeleteGroup 删除团队
	DeleteGroup(context.Context, *DeleteGroupRequest) (*EmptyReply, error)
	// DeleteResource 删除菜单
	DeleteResource(context.Context, *DeleteResourceRequest) (*EmptyReply, error)
	// DeleteRole 删除角色
	DeleteRole(context.Context, *DeleteRoleRequest) (*EmptyReply, error)
	// ImportResource 导入菜单
	ImportResource(context.Context, *ImportResourceRequest) (*EmptyReply, error)
	// ListGroup 获取团队列表
	ListGroup(context.Context, *ListGroupRequest) (*ListGroupReply, error)
	// ListGroupMember 获取团队成员列表
	ListGroupMember(context.Context, *ListGroupMemberRequest) (*ListGroupMemberReply, error)
	// ListResource 获取菜单列表
	ListResource(context.Context, *ListResourceRequest) (*ListResourceReply, error)
	// ListRole 获取角色列表
	ListRole(context.Context, *ListRoleRequest) (*ListRoleReply, error)
	// ListRoleMember 角色成员列表
	ListRoleMember(context.Context, *ListRoleMemberRequest) (*ListRoleMemberReply, error)
	// ListRolePermission 获取角色权限列表
	ListRolePermission(context.Context, *ListRolePermissionRequest) (*ListRolePermissionReply, error)
	// SaveGroup 保存团队信息
	SaveGroup(context.Context, *SaveGroupRequest) (*SaveGroupReply, error)
	// SaveGroupMember 保存团队成员信息
	SaveGroupMember(context.Context, *SaveGroupMemberRequest) (*EmptyReply, error)
	// SaveResource 保存菜单
	SaveResource(context.Context, *SaveResourceRequest) (*SaveResourceReply, error)
	// SaveRole 保存角色信息
	SaveRole(context.Context, *SaveRoleRequest) (*SaveRoleReply, error)
	// SaveRolePermission 保存角色权限
	SaveRolePermission(context.Context, *SaveRolePermissionRequest) (*EmptyReply, error)
}

func RegisterPermissionHTTPServer(s *http.Server, srv PermissionHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/permission/group/list", _Permission_ListGroup0_HTTP_Handler(srv))
	r.POST("/v1/permission/group/save", _Permission_SaveGroup0_HTTP_Handler(srv))
	r.DELETE("/v1/permission/group/delete", _Permission_DeleteGroup0_HTTP_Handler(srv))
	r.GET("/v1/permission/group/member/list", _Permission_ListGroupMember0_HTTP_Handler(srv))
	r.POST("/v1/permission/group/member/save", _Permission_SaveGroupMember0_HTTP_Handler(srv))
	r.GET("/v1/permission/role/list", _Permission_ListRole0_HTTP_Handler(srv))
	r.POST("/v1/permission/role/save", _Permission_SaveRole0_HTTP_Handler(srv))
	r.DELETE("/v1/permission/role/delete", _Permission_DeleteRole0_HTTP_Handler(srv))
	r.GET("/v1/permission/role/permission/list", _Permission_ListRolePermission0_HTTP_Handler(srv))
	r.POST("/v1/permission/role/permission/save", _Permission_SaveRolePermission0_HTTP_Handler(srv))
	r.GET("/v1/permission/role/member/list", _Permission_ListRoleMember0_HTTP_Handler(srv))
	r.GET("/v1/permission/resource/list", _Permission_ListResource0_HTTP_Handler(srv))
	r.POST("/v1/permission/resource/save", _Permission_SaveResource0_HTTP_Handler(srv))
	r.DELETE("/v1/permission/resource/delete", _Permission_DeleteResource0_HTTP_Handler(srv))
	r.POST("/v1/permission/resource/import", _Permission_ImportResource0_HTTP_Handler(srv))
}

func _Permission_ListGroup0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionListGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGroup(ctx, req.(*ListGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_SaveGroup0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionSaveGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveGroup(ctx, req.(*SaveGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveGroupReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_DeleteGroup0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionDeleteGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGroup(ctx, req.(*DeleteGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_ListGroupMember0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGroupMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionListGroupMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGroupMember(ctx, req.(*ListGroupMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGroupMemberReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_SaveGroupMember0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveGroupMemberRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionSaveGroupMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveGroupMember(ctx, req.(*SaveGroupMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_ListRole0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionListRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRole(ctx, req.(*ListRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoleReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_SaveRole0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionSaveRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveRole(ctx, req.(*SaveRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveRoleReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_DeleteRole0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionDeleteRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRole(ctx, req.(*DeleteRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_ListRolePermission0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolePermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionListRolePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRolePermission(ctx, req.(*ListRolePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRolePermissionReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_SaveRolePermission0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveRolePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionSaveRolePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveRolePermission(ctx, req.(*SaveRolePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_ListRoleMember0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoleMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionListRoleMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoleMember(ctx, req.(*ListRoleMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoleMemberReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_ListResource0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListResourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionListResource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListResource(ctx, req.(*ListResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListResourceReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_SaveResource0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveResourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionSaveResource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveResource(ctx, req.(*SaveResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveResourceReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_DeleteResource0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteResourceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionDeleteResource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteResource(ctx, req.(*DeleteResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_ImportResource0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportResourceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionImportResource)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportResource(ctx, req.(*ImportResourceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmptyReply)
		return ctx.Result(200, reply)
	}
}

type PermissionHTTPClient interface {
	// DeleteGroup 删除团队
	DeleteGroup(ctx context.Context, req *DeleteGroupRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// DeleteResource 删除菜单
	DeleteResource(ctx context.Context, req *DeleteResourceRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// DeleteRole 删除角色
	DeleteRole(ctx context.Context, req *DeleteRoleRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// ImportResource 导入菜单
	ImportResource(ctx context.Context, req *ImportResourceRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// ListGroup 获取团队列表
	ListGroup(ctx context.Context, req *ListGroupRequest, opts ...http.CallOption) (rsp *ListGroupReply, err error)
	// ListGroupMember 获取团队成员列表
	ListGroupMember(ctx context.Context, req *ListGroupMemberRequest, opts ...http.CallOption) (rsp *ListGroupMemberReply, err error)
	// ListResource 获取菜单列表
	ListResource(ctx context.Context, req *ListResourceRequest, opts ...http.CallOption) (rsp *ListResourceReply, err error)
	// ListRole 获取角色列表
	ListRole(ctx context.Context, req *ListRoleRequest, opts ...http.CallOption) (rsp *ListRoleReply, err error)
	// ListRoleMember 角色成员列表
	ListRoleMember(ctx context.Context, req *ListRoleMemberRequest, opts ...http.CallOption) (rsp *ListRoleMemberReply, err error)
	// ListRolePermission 获取角色权限列表
	ListRolePermission(ctx context.Context, req *ListRolePermissionRequest, opts ...http.CallOption) (rsp *ListRolePermissionReply, err error)
	// SaveGroup 保存团队信息
	SaveGroup(ctx context.Context, req *SaveGroupRequest, opts ...http.CallOption) (rsp *SaveGroupReply, err error)
	// SaveGroupMember 保存团队成员信息
	SaveGroupMember(ctx context.Context, req *SaveGroupMemberRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
	// SaveResource 保存菜单
	SaveResource(ctx context.Context, req *SaveResourceRequest, opts ...http.CallOption) (rsp *SaveResourceReply, err error)
	// SaveRole 保存角色信息
	SaveRole(ctx context.Context, req *SaveRoleRequest, opts ...http.CallOption) (rsp *SaveRoleReply, err error)
	// SaveRolePermission 保存角色权限
	SaveRolePermission(ctx context.Context, req *SaveRolePermissionRequest, opts ...http.CallOption) (rsp *EmptyReply, err error)
}

type PermissionHTTPClientImpl struct {
	cc *http.Client
}

func NewPermissionHTTPClient(client *http.Client) PermissionHTTPClient {
	return &PermissionHTTPClientImpl{client}
}

// DeleteGroup 删除团队
func (c *PermissionHTTPClientImpl) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/permission/group/delete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionDeleteGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteResource 删除菜单
func (c *PermissionHTTPClientImpl) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/permission/resource/delete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionDeleteResource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteRole 删除角色
func (c *PermissionHTTPClientImpl) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/permission/role/delete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionDeleteRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ImportResource 导入菜单
func (c *PermissionHTTPClientImpl) ImportResource(ctx context.Context, in *ImportResourceRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/permission/resource/import"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionImportResource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGroup 获取团队列表
func (c *PermissionHTTPClientImpl) ListGroup(ctx context.Context, in *ListGroupRequest, opts ...http.CallOption) (*ListGroupReply, error) {
	var out ListGroupReply
	pattern := "/v1/permission/group/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionListGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGroupMember 获取团队成员列表
func (c *PermissionHTTPClientImpl) ListGroupMember(ctx context.Context, in *ListGroupMemberRequest, opts ...http.CallOption) (*ListGroupMemberReply, error) {
	var out ListGroupMemberReply
	pattern := "/v1/permission/group/member/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionListGroupMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListResource 获取菜单列表
func (c *PermissionHTTPClientImpl) ListResource(ctx context.Context, in *ListResourceRequest, opts ...http.CallOption) (*ListResourceReply, error) {
	var out ListResourceReply
	pattern := "/v1/permission/resource/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionListResource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRole 获取角色列表
func (c *PermissionHTTPClientImpl) ListRole(ctx context.Context, in *ListRoleRequest, opts ...http.CallOption) (*ListRoleReply, error) {
	var out ListRoleReply
	pattern := "/v1/permission/role/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionListRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRoleMember 角色成员列表
func (c *PermissionHTTPClientImpl) ListRoleMember(ctx context.Context, in *ListRoleMemberRequest, opts ...http.CallOption) (*ListRoleMemberReply, error) {
	var out ListRoleMemberReply
	pattern := "/v1/permission/role/member/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionListRoleMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRolePermission 获取角色权限列表
func (c *PermissionHTTPClientImpl) ListRolePermission(ctx context.Context, in *ListRolePermissionRequest, opts ...http.CallOption) (*ListRolePermissionReply, error) {
	var out ListRolePermissionReply
	pattern := "/v1/permission/role/permission/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionListRolePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveGroup 保存团队信息
func (c *PermissionHTTPClientImpl) SaveGroup(ctx context.Context, in *SaveGroupRequest, opts ...http.CallOption) (*SaveGroupReply, error) {
	var out SaveGroupReply
	pattern := "/v1/permission/group/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionSaveGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveGroupMember 保存团队成员信息
func (c *PermissionHTTPClientImpl) SaveGroupMember(ctx context.Context, in *SaveGroupMemberRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/permission/group/member/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionSaveGroupMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveResource 保存菜单
func (c *PermissionHTTPClientImpl) SaveResource(ctx context.Context, in *SaveResourceRequest, opts ...http.CallOption) (*SaveResourceReply, error) {
	var out SaveResourceReply
	pattern := "/v1/permission/resource/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionSaveResource))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveRole 保存角色信息
func (c *PermissionHTTPClientImpl) SaveRole(ctx context.Context, in *SaveRoleRequest, opts ...http.CallOption) (*SaveRoleReply, error) {
	var out SaveRoleReply
	pattern := "/v1/permission/role/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionSaveRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaveRolePermission 保存角色权限
func (c *PermissionHTTPClientImpl) SaveRolePermission(ctx context.Context, in *SaveRolePermissionRequest, opts ...http.CallOption) (*EmptyReply, error) {
	var out EmptyReply
	pattern := "/v1/permission/role/permission/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionSaveRolePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
