// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: admin/v1/permission.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Permission_ListGroup_FullMethodName          = "/admin.v1.Permission/ListGroup"
	Permission_SaveGroup_FullMethodName          = "/admin.v1.Permission/SaveGroup"
	Permission_DeleteGroup_FullMethodName        = "/admin.v1.Permission/DeleteGroup"
	Permission_ListGroupMember_FullMethodName    = "/admin.v1.Permission/ListGroupMember"
	Permission_SaveGroupMember_FullMethodName    = "/admin.v1.Permission/SaveGroupMember"
	Permission_ListRole_FullMethodName           = "/admin.v1.Permission/ListRole"
	Permission_SaveRole_FullMethodName           = "/admin.v1.Permission/SaveRole"
	Permission_DeleteRole_FullMethodName         = "/admin.v1.Permission/DeleteRole"
	Permission_ListRolePermission_FullMethodName = "/admin.v1.Permission/ListRolePermission"
	Permission_SaveRolePermission_FullMethodName = "/admin.v1.Permission/SaveRolePermission"
	Permission_ListRoleMember_FullMethodName     = "/admin.v1.Permission/ListRoleMember"
	Permission_ListResource_FullMethodName       = "/admin.v1.Permission/ListResource"
	Permission_SaveResource_FullMethodName       = "/admin.v1.Permission/SaveResource"
	Permission_DeleteResource_FullMethodName     = "/admin.v1.Permission/DeleteResource"
	Permission_ImportResource_FullMethodName     = "/admin.v1.Permission/ImportResource"
)

// PermissionClient is the client API for Permission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionClient interface {
	// 获取团队列表
	ListGroup(ctx context.Context, in *ListGroupRequest, opts ...grpc.CallOption) (*ListGroupReply, error)
	// 保存团队信息
	SaveGroup(ctx context.Context, in *SaveGroupRequest, opts ...grpc.CallOption) (*SaveGroupReply, error)
	// 删除团队
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 获取团队成员列表
	ListGroupMember(ctx context.Context, in *ListGroupMemberRequest, opts ...grpc.CallOption) (*ListGroupMemberReply, error)
	// 保存团队成员信息
	SaveGroupMember(ctx context.Context, in *SaveGroupMemberRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 获取角色列表
	ListRole(ctx context.Context, in *ListRoleRequest, opts ...grpc.CallOption) (*ListRoleReply, error)
	// 保存角色信息
	SaveRole(ctx context.Context, in *SaveRoleRequest, opts ...grpc.CallOption) (*SaveRoleReply, error)
	// 删除角色
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 获取角色权限列表
	ListRolePermission(ctx context.Context, in *ListRolePermissionRequest, opts ...grpc.CallOption) (*ListRolePermissionReply, error)
	// 保存角色权限
	SaveRolePermission(ctx context.Context, in *SaveRolePermissionRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 角色成员列表
	ListRoleMember(ctx context.Context, in *ListRoleMemberRequest, opts ...grpc.CallOption) (*ListRoleMemberReply, error)
	// 获取菜单列表
	ListResource(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*ListResourceReply, error)
	// 保存菜单
	SaveResource(ctx context.Context, in *SaveResourceRequest, opts ...grpc.CallOption) (*SaveResourceReply, error)
	// 删除菜单
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	// 导入菜单
	ImportResource(ctx context.Context, in *ImportResourceRequest, opts ...grpc.CallOption) (*EmptyReply, error)
}

type permissionClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionClient(cc grpc.ClientConnInterface) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) ListGroup(ctx context.Context, in *ListGroupRequest, opts ...grpc.CallOption) (*ListGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupReply)
	err := c.cc.Invoke(ctx, Permission_ListGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) SaveGroup(ctx context.Context, in *SaveGroupRequest, opts ...grpc.CallOption) (*SaveGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGroupReply)
	err := c.cc.Invoke(ctx, Permission_SaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Permission_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) ListGroupMember(ctx context.Context, in *ListGroupMemberRequest, opts ...grpc.CallOption) (*ListGroupMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupMemberReply)
	err := c.cc.Invoke(ctx, Permission_ListGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) SaveGroupMember(ctx context.Context, in *SaveGroupMemberRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Permission_SaveGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) ListRole(ctx context.Context, in *ListRoleRequest, opts ...grpc.CallOption) (*ListRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleReply)
	err := c.cc.Invoke(ctx, Permission_ListRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) SaveRole(ctx context.Context, in *SaveRoleRequest, opts ...grpc.CallOption) (*SaveRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRoleReply)
	err := c.cc.Invoke(ctx, Permission_SaveRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Permission_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) ListRolePermission(ctx context.Context, in *ListRolePermissionRequest, opts ...grpc.CallOption) (*ListRolePermissionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolePermissionReply)
	err := c.cc.Invoke(ctx, Permission_ListRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) SaveRolePermission(ctx context.Context, in *SaveRolePermissionRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Permission_SaveRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) ListRoleMember(ctx context.Context, in *ListRoleMemberRequest, opts ...grpc.CallOption) (*ListRoleMemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleMemberReply)
	err := c.cc.Invoke(ctx, Permission_ListRoleMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) ListResource(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*ListResourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceReply)
	err := c.cc.Invoke(ctx, Permission_ListResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) SaveResource(ctx context.Context, in *SaveResourceRequest, opts ...grpc.CallOption) (*SaveResourceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResourceReply)
	err := c.cc.Invoke(ctx, Permission_SaveResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Permission_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) ImportResource(ctx context.Context, in *ImportResourceRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Permission_ImportResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServer is the server API for Permission service.
// All implementations must embed UnimplementedPermissionServer
// for forward compatibility.
type PermissionServer interface {
	// 获取团队列表
	ListGroup(context.Context, *ListGroupRequest) (*ListGroupReply, error)
	// 保存团队信息
	SaveGroup(context.Context, *SaveGroupRequest) (*SaveGroupReply, error)
	// 删除团队
	DeleteGroup(context.Context, *DeleteGroupRequest) (*EmptyReply, error)
	// 获取团队成员列表
	ListGroupMember(context.Context, *ListGroupMemberRequest) (*ListGroupMemberReply, error)
	// 保存团队成员信息
	SaveGroupMember(context.Context, *SaveGroupMemberRequest) (*EmptyReply, error)
	// 获取角色列表
	ListRole(context.Context, *ListRoleRequest) (*ListRoleReply, error)
	// 保存角色信息
	SaveRole(context.Context, *SaveRoleRequest) (*SaveRoleReply, error)
	// 删除角色
	DeleteRole(context.Context, *DeleteRoleRequest) (*EmptyReply, error)
	// 获取角色权限列表
	ListRolePermission(context.Context, *ListRolePermissionRequest) (*ListRolePermissionReply, error)
	// 保存角色权限
	SaveRolePermission(context.Context, *SaveRolePermissionRequest) (*EmptyReply, error)
	// 角色成员列表
	ListRoleMember(context.Context, *ListRoleMemberRequest) (*ListRoleMemberReply, error)
	// 获取菜单列表
	ListResource(context.Context, *ListResourceRequest) (*ListResourceReply, error)
	// 保存菜单
	SaveResource(context.Context, *SaveResourceRequest) (*SaveResourceReply, error)
	// 删除菜单
	DeleteResource(context.Context, *DeleteResourceRequest) (*EmptyReply, error)
	// 导入菜单
	ImportResource(context.Context, *ImportResourceRequest) (*EmptyReply, error)
	mustEmbedUnimplementedPermissionServer()
}

// UnimplementedPermissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionServer struct{}

func (UnimplementedPermissionServer) ListGroup(context.Context, *ListGroupRequest) (*ListGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroup not implemented")
}
func (UnimplementedPermissionServer) SaveGroup(context.Context, *SaveGroupRequest) (*SaveGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGroup not implemented")
}
func (UnimplementedPermissionServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedPermissionServer) ListGroupMember(context.Context, *ListGroupMemberRequest) (*ListGroupMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroupMember not implemented")
}
func (UnimplementedPermissionServer) SaveGroupMember(context.Context, *SaveGroupMemberRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveGroupMember not implemented")
}
func (UnimplementedPermissionServer) ListRole(context.Context, *ListRoleRequest) (*ListRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRole not implemented")
}
func (UnimplementedPermissionServer) SaveRole(context.Context, *SaveRoleRequest) (*SaveRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRole not implemented")
}
func (UnimplementedPermissionServer) DeleteRole(context.Context, *DeleteRoleRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedPermissionServer) ListRolePermission(context.Context, *ListRolePermissionRequest) (*ListRolePermissionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRolePermission not implemented")
}
func (UnimplementedPermissionServer) SaveRolePermission(context.Context, *SaveRolePermissionRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRolePermission not implemented")
}
func (UnimplementedPermissionServer) ListRoleMember(context.Context, *ListRoleMemberRequest) (*ListRoleMemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoleMember not implemented")
}
func (UnimplementedPermissionServer) ListResource(context.Context, *ListResourceRequest) (*ListResourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResource not implemented")
}
func (UnimplementedPermissionServer) SaveResource(context.Context, *SaveResourceRequest) (*SaveResourceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveResource not implemented")
}
func (UnimplementedPermissionServer) DeleteResource(context.Context, *DeleteResourceRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedPermissionServer) ImportResource(context.Context, *ImportResourceRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportResource not implemented")
}
func (UnimplementedPermissionServer) mustEmbedUnimplementedPermissionServer() {}
func (UnimplementedPermissionServer) testEmbeddedByValue()                    {}

// UnsafePermissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServer will
// result in compilation errors.
type UnsafePermissionServer interface {
	mustEmbedUnimplementedPermissionServer()
}

func RegisterPermissionServer(s grpc.ServiceRegistrar, srv PermissionServer) {
	// If the following call pancis, it indicates UnimplementedPermissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Permission_ServiceDesc, srv)
}

func _Permission_ListGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ListGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ListGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ListGroup(ctx, req.(*ListGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_SaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).SaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_SaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).SaveGroup(ctx, req.(*SaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_ListGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ListGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ListGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ListGroupMember(ctx, req.(*ListGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_SaveGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).SaveGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_SaveGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).SaveGroupMember(ctx, req.(*SaveGroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_ListRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ListRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ListRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ListRole(ctx, req.(*ListRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_SaveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).SaveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_SaveRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).SaveRole(ctx, req.(*SaveRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_ListRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ListRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ListRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ListRolePermission(ctx, req.(*ListRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_SaveRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).SaveRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_SaveRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).SaveRolePermission(ctx, req.(*SaveRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_ListRoleMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ListRoleMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ListRoleMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ListRoleMember(ctx, req.(*ListRoleMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_ListResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ListResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ListResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ListResource(ctx, req.(*ListResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_SaveResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).SaveResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_SaveResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).SaveResource(ctx, req.(*SaveResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_ImportResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).ImportResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_ImportResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).ImportResource(ctx, req.(*ImportResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Permission_ServiceDesc is the grpc.ServiceDesc for Permission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Permission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.Permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroup",
			Handler:    _Permission_ListGroup_Handler,
		},
		{
			MethodName: "SaveGroup",
			Handler:    _Permission_SaveGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _Permission_DeleteGroup_Handler,
		},
		{
			MethodName: "ListGroupMember",
			Handler:    _Permission_ListGroupMember_Handler,
		},
		{
			MethodName: "SaveGroupMember",
			Handler:    _Permission_SaveGroupMember_Handler,
		},
		{
			MethodName: "ListRole",
			Handler:    _Permission_ListRole_Handler,
		},
		{
			MethodName: "SaveRole",
			Handler:    _Permission_SaveRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _Permission_DeleteRole_Handler,
		},
		{
			MethodName: "ListRolePermission",
			Handler:    _Permission_ListRolePermission_Handler,
		},
		{
			MethodName: "SaveRolePermission",
			Handler:    _Permission_SaveRolePermission_Handler,
		},
		{
			MethodName: "ListRoleMember",
			Handler:    _Permission_ListRoleMember_Handler,
		},
		{
			MethodName: "ListResource",
			Handler:    _Permission_ListResource_Handler,
		},
		{
			MethodName: "SaveResource",
			Handler:    _Permission_SaveResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _Permission_DeleteResource_Handler,
		},
		{
			MethodName: "ImportResource",
			Handler:    _Permission_ImportResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/permission.proto",
}
