server:
  http:
    addr: ":8202"
  grpc:
    addr: ":9202"
data:
  global:
    admin_database:
      driver: mysql
      source: "root:123456@tcp(localhost:3306)/syntra?parseTime=true&loc=Asia%2FShanghai&charset=utf8mb4&collation=utf8mb4_0900_ai_ci"
    redis:
      addr: "127.0.0.1:6379"
      password: ""
      db: 0
security:
  jwt_secret: change-me-in-production
  jwt_ttl: 1209600
  jwt_skip_paths:
    - POST:/v1/user/login
  third_paths: []
permission:
  close_permission: false
  skip_paths:
    - POST:/v1/user/login
    - POST:/v1/user/logout
    - GET:/v1/user/info
    - GET:/v1/optimizer/list
  data_permission_paths: []
